// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * <pre>
 * NOTE: Deprecated now that BulkCheckPermission has been promoted to the stable API as "CheckBulkPermission".
 * </pre>
 *
 * Protobuf type {@code authzed.api.v1.BulkCheckPermissionRequest}
 */
@com.google.protobuf.Generated
public final class BulkCheckPermissionRequest extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.BulkCheckPermissionRequest)
        BulkCheckPermissionRequestOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", BulkCheckPermissionRequest.class.getName());
    }

    // Use BulkCheckPermissionRequest.newBuilder() to construct.
    private BulkCheckPermissionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private BulkCheckPermissionRequest() {
        items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.ExperimentalServiceOuterClass.internal_static_authzed_api_v1_BulkCheckPermissionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.ExperimentalServiceOuterClass.internal_static_authzed_api_v1_BulkCheckPermissionRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.BulkCheckPermissionRequest.class,
                        com.authzed.api.v1.BulkCheckPermissionRequest.Builder.class);
    }

    private int bitField0_;

    public static final int CONSISTENCY_FIELD_NUMBER = 1;

    private com.authzed.api.v1.Consistency consistency_;

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return Whether the consistency field is set.
     */
    @java.lang.Override
    public boolean hasConsistency() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return The consistency.
     */
    @java.lang.Override
    public com.authzed.api.v1.Consistency getConsistency() {
        return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder() {
        return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private java.util.List<com.authzed.api.v1.BulkCheckPermissionRequestItem> items_;

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.List<com.authzed.api.v1.BulkCheckPermissionRequestItem> getItemsList() {
        return items_;
    }

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.List<? extends com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder> getItemsOrBuilderList() {
        return items_;
    }

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    @java.lang.Deprecated
    public int getItemsCount() {
        return items_.size();
    }

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    @java.lang.Deprecated
    public com.authzed.api.v1.BulkCheckPermissionRequestItem getItems(int index) {
        return items_.get(index);
    }

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    @java.lang.Deprecated
    public com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder getItemsOrBuilder(int index) {
        return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getConsistency());
        }
        for (int i = 0; i < items_.size(); i++) {
            output.writeMessage(2, items_.get(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getConsistency());
        }
        for (int i = 0; i < items_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, items_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.BulkCheckPermissionRequest)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.BulkCheckPermissionRequest other = (com.authzed.api.v1.BulkCheckPermissionRequest) obj;
        if (hasConsistency() != other.hasConsistency())
            return false;
        if (hasConsistency()) {
            if (!getConsistency().equals(other.getConsistency()))
                return false;
        }
        if (!getItemsList().equals(other.getItemsList()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasConsistency()) {
            hash = (37 * hash) + CONSISTENCY_FIELD_NUMBER;
            hash = (53 * hash) + getConsistency().hashCode();
        }
        if (getItemsCount() > 0) {
            hash = (37 * hash) + ITEMS_FIELD_NUMBER;
            hash = (53 * hash) + getItemsList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.BulkCheckPermissionRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * NOTE: Deprecated now that BulkCheckPermission has been promoted to the stable API as "CheckBulkPermission".
     * </pre>
     *
     * Protobuf type {@code authzed.api.v1.BulkCheckPermissionRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.BulkCheckPermissionRequest)
            com.authzed.api.v1.BulkCheckPermissionRequestOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.ExperimentalServiceOuterClass.internal_static_authzed_api_v1_BulkCheckPermissionRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.ExperimentalServiceOuterClass.internal_static_authzed_api_v1_BulkCheckPermissionRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.BulkCheckPermissionRequest.class,
                            com.authzed.api.v1.BulkCheckPermissionRequest.Builder.class);
        }

        // Construct using com.authzed.api.v1.BulkCheckPermissionRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                internalGetConsistencyFieldBuilder();
                internalGetItemsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            consistency_ = null;
            if (consistencyBuilder_ != null) {
                consistencyBuilder_.dispose();
                consistencyBuilder_ = null;
            }
            if (itemsBuilder_ == null) {
                items_ = java.util.Collections.emptyList();
            } else {
                items_ = null;
                itemsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.ExperimentalServiceOuterClass.internal_static_authzed_api_v1_BulkCheckPermissionRequest_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.BulkCheckPermissionRequest getDefaultInstanceForType() {
            return com.authzed.api.v1.BulkCheckPermissionRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.BulkCheckPermissionRequest build() {
            com.authzed.api.v1.BulkCheckPermissionRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.BulkCheckPermissionRequest buildPartial() {
            com.authzed.api.v1.BulkCheckPermissionRequest result = new com.authzed.api.v1.BulkCheckPermissionRequest(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(com.authzed.api.v1.BulkCheckPermissionRequest result) {
            if (itemsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    items_ = java.util.Collections.unmodifiableList(items_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.items_ = items_;
            } else {
                result.items_ = itemsBuilder_.build();
            }
        }

        private void buildPartial0(com.authzed.api.v1.BulkCheckPermissionRequest result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.consistency_ = consistencyBuilder_ == null ? consistency_ : consistencyBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.BulkCheckPermissionRequest) {
                return mergeFrom((com.authzed.api.v1.BulkCheckPermissionRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.BulkCheckPermissionRequest other) {
            if (other == com.authzed.api.v1.BulkCheckPermissionRequest.getDefaultInstance())
                return this;
            if (other.hasConsistency()) {
                mergeConsistency(other.getConsistency());
            }
            if (itemsBuilder_ == null) {
                if (!other.items_.isEmpty()) {
                    if (items_.isEmpty()) {
                        items_ = other.items_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureItemsIsMutable();
                        items_.addAll(other.items_);
                    }
                    onChanged();
                }
            } else {
                if (!other.items_.isEmpty()) {
                    if (itemsBuilder_.isEmpty()) {
                        itemsBuilder_.dispose();
                        itemsBuilder_ = null;
                        items_ = other.items_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        itemsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                ? internalGetItemsFieldBuilder()
                                : null;
                    } else {
                        itemsBuilder_.addAllMessages(other.items_);
                    }
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(internalGetConsistencyFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            com.authzed.api.v1.BulkCheckPermissionRequestItem m = input
                                    .readMessage(com.authzed.api.v1.BulkCheckPermissionRequestItem.parser(), extensionRegistry);
                            if (itemsBuilder_ == null) {
                                ensureItemsIsMutable();
                                items_.add(m);
                            } else {
                                itemsBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private com.authzed.api.v1.Consistency consistency_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder> consistencyBuilder_;

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         *
         * @return Whether the consistency field is set.
         */
        public boolean hasConsistency() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         *
         * @return The consistency.
         */
        public com.authzed.api.v1.Consistency getConsistency() {
            if (consistencyBuilder_ == null) {
                return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
            } else {
                return consistencyBuilder_.getMessage();
            }
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder setConsistency(com.authzed.api.v1.Consistency value) {
            if (consistencyBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                consistency_ = value;
            } else {
                consistencyBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder setConsistency(com.authzed.api.v1.Consistency.Builder builderForValue) {
            if (consistencyBuilder_ == null) {
                consistency_ = builderForValue.build();
            } else {
                consistencyBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder mergeConsistency(com.authzed.api.v1.Consistency value) {
            if (consistencyBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && consistency_ != null
                        && consistency_ != com.authzed.api.v1.Consistency.getDefaultInstance()) {
                    getConsistencyBuilder().mergeFrom(value);
                } else {
                    consistency_ = value;
                }
            } else {
                consistencyBuilder_.mergeFrom(value);
            }
            if (consistency_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder clearConsistency() {
            bitField0_ = (bitField0_ & ~0x00000001);
            consistency_ = null;
            if (consistencyBuilder_ != null) {
                consistencyBuilder_.dispose();
                consistencyBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public com.authzed.api.v1.Consistency.Builder getConsistencyBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return internalGetConsistencyFieldBuilder().getBuilder();
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder() {
            if (consistencyBuilder_ != null) {
                return consistencyBuilder_.getMessageOrBuilder();
            } else {
                return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
            }
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder> internalGetConsistencyFieldBuilder() {
            if (consistencyBuilder_ == null) {
                consistencyBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder>(
                        getConsistency(), getParentForChildren(), isClean());
                consistency_ = null;
            }
            return consistencyBuilder_;
        }

        private java.util.List<com.authzed.api.v1.BulkCheckPermissionRequestItem> items_ = java.util.Collections.emptyList();

        private void ensureItemsIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                items_ = new java.util.ArrayList<com.authzed.api.v1.BulkCheckPermissionRequestItem>(items_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.BulkCheckPermissionRequestItem, com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder, com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder> itemsBuilder_;

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public java.util.List<com.authzed.api.v1.BulkCheckPermissionRequestItem> getItemsList() {
            if (itemsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(items_);
            } else {
                return itemsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public int getItemsCount() {
            if (itemsBuilder_ == null) {
                return items_.size();
            } else {
                return itemsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public com.authzed.api.v1.BulkCheckPermissionRequestItem getItems(int index) {
            if (itemsBuilder_ == null) {
                return items_.get(index);
            } else {
                return itemsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder setItems(int index, com.authzed.api.v1.BulkCheckPermissionRequestItem value) {
            if (itemsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureItemsIsMutable();
                items_.set(index, value);
                onChanged();
            } else {
                itemsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder setItems(int index, com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder builderForValue) {
            if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.set(index, builderForValue.build());
                onChanged();
            } else {
                itemsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder addItems(com.authzed.api.v1.BulkCheckPermissionRequestItem value) {
            if (itemsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureItemsIsMutable();
                items_.add(value);
                onChanged();
            } else {
                itemsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder addItems(int index, com.authzed.api.v1.BulkCheckPermissionRequestItem value) {
            if (itemsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureItemsIsMutable();
                items_.add(index, value);
                onChanged();
            } else {
                itemsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder addItems(com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder builderForValue) {
            if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(builderForValue.build());
                onChanged();
            } else {
                itemsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder addItems(int index, com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder builderForValue) {
            if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(index, builderForValue.build());
                onChanged();
            } else {
                itemsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder addAllItems(java.lang.Iterable<? extends com.authzed.api.v1.BulkCheckPermissionRequestItem> values) {
            if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, items_);
                onChanged();
            } else {
                itemsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder clearItems() {
            if (itemsBuilder_ == null) {
                items_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                itemsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public Builder removeItems(int index) {
            if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.remove(index);
                onChanged();
            } else {
                itemsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder getItemsBuilder(int index) {
            return internalGetItemsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder getItemsOrBuilder(int index) {
            if (itemsBuilder_ == null) {
                return items_.get(index);
            } else {
                return itemsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public java.util.List<? extends com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder> getItemsOrBuilderList() {
            if (itemsBuilder_ != null) {
                return itemsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(items_);
            }
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder addItemsBuilder() {
            return internalGetItemsFieldBuilder()
                    .addBuilder(com.authzed.api.v1.BulkCheckPermissionRequestItem.getDefaultInstance());
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder addItemsBuilder(int index) {
            return internalGetItemsFieldBuilder().addBuilder(index,
                    com.authzed.api.v1.BulkCheckPermissionRequestItem.getDefaultInstance());
        }

        /**
         * <code>repeated .authzed.api.v1.BulkCheckPermissionRequestItem items = 2 [deprecated = true, (.validate.rules) = { ... }</code>
         */
        @java.lang.Deprecated
        public java.util.List<com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder> getItemsBuilderList() {
            return internalGetItemsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.BulkCheckPermissionRequestItem, com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder, com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder> internalGetItemsFieldBuilder() {
            if (itemsBuilder_ == null) {
                itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.BulkCheckPermissionRequestItem, com.authzed.api.v1.BulkCheckPermissionRequestItem.Builder, com.authzed.api.v1.BulkCheckPermissionRequestItemOrBuilder>(
                        items_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
                items_ = null;
            }
            return itemsBuilder_;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.BulkCheckPermissionRequest)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.BulkCheckPermissionRequest)
    private static final com.authzed.api.v1.BulkCheckPermissionRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.BulkCheckPermissionRequest();
    }

    public static com.authzed.api.v1.BulkCheckPermissionRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BulkCheckPermissionRequest> PARSER = new com.google.protobuf.AbstractParser<BulkCheckPermissionRequest>() {

        @java.lang.Override
        public BulkCheckPermissionRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<BulkCheckPermissionRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BulkCheckPermissionRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.BulkCheckPermissionRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
