// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface BulkCheckPermissionResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.BulkCheckPermissionResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the checkedAt field is set.
     */
    boolean hasCheckedAt();

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The checkedAt.
     */
    com.authzed.api.v1.ZedToken getCheckedAt();

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getCheckedAtOrBuilder();

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionPair pairs = 2 [(.validate.rules) = { ... }</code>
     */
    java.util.List<com.authzed.api.v1.BulkCheckPermissionPair> getPairsList();

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionPair pairs = 2 [(.validate.rules) = { ... }</code>
     */
    com.authzed.api.v1.BulkCheckPermissionPair getPairs(int index);

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionPair pairs = 2 [(.validate.rules) = { ... }</code>
     */
    int getPairsCount();

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionPair pairs = 2 [(.validate.rules) = { ... }</code>
     */
    java.util.List<? extends com.authzed.api.v1.BulkCheckPermissionPairOrBuilder> getPairsOrBuilderList();

    /**
     * <code>repeated .authzed.api.v1.BulkCheckPermissionPair pairs = 2 [(.validate.rules) = { ... }</code>
     */
    com.authzed.api.v1.BulkCheckPermissionPairOrBuilder getPairsOrBuilder(int index);
}
