// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface BulkImportRelationshipsResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.BulkImportRelationshipsResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 num_loaded = 1;</code>
     *
     * @return The numLoaded.
     */
    long getNumLoaded();
}
