// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/permission_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface CheckPermissionResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.CheckPermissionResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the checkedAt field is set.
     */
    boolean hasCheckedAt();

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The checkedAt.
     */
    com.authzed.api.v1.ZedToken getCheckedAt();

    /**
     * <code>.authzed.api.v1.ZedToken checked_at = 1 [(.validate.rules) = { ... }</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getCheckedAtOrBuilder();

    /**
     * <pre>
     * Permissionship communicates whether or not the subject has the requested
     * permission or has a relationship with the given resource, over the given
     * relation.
     *
     * This value will be authzed.api.v1.PERMISSIONSHIP_HAS_PERMISSION if the
     * requested subject is a member of the computed permission set or there
     * exists a relationship with the requested relation from the given resource
     * to the given subject.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckPermissionResponse.Permissionship permissionship = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The enum numeric value on the wire for permissionship.
     */
    int getPermissionshipValue();

    /**
     * <pre>
     * Permissionship communicates whether or not the subject has the requested
     * permission or has a relationship with the given resource, over the given
     * relation.
     *
     * This value will be authzed.api.v1.PERMISSIONSHIP_HAS_PERMISSION if the
     * requested subject is a member of the computed permission set or there
     * exists a relationship with the requested relation from the given resource
     * to the given subject.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckPermissionResponse.Permissionship permissionship = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The permissionship.
     */
    com.authzed.api.v1.CheckPermissionResponse.Permissionship getPermissionship();

    /**
     * <pre>
     * partial_caveat_info holds information of a partially-evaluated caveated response
     * </pre>
     *
     * <code>.authzed.api.v1.PartialCaveatInfo partial_caveat_info = 3 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the partialCaveatInfo field is set.
     */
    boolean hasPartialCaveatInfo();

    /**
     * <pre>
     * partial_caveat_info holds information of a partially-evaluated caveated response
     * </pre>
     *
     * <code>.authzed.api.v1.PartialCaveatInfo partial_caveat_info = 3 [(.validate.rules) = { ... }</code>
     *
     * @return The partialCaveatInfo.
     */
    com.authzed.api.v1.PartialCaveatInfo getPartialCaveatInfo();

    /**
     * <pre>
     * partial_caveat_info holds information of a partially-evaluated caveated response
     * </pre>
     *
     * <code>.authzed.api.v1.PartialCaveatInfo partial_caveat_info = 3 [(.validate.rules) = { ... }</code>
     */
    com.authzed.api.v1.PartialCaveatInfoOrBuilder getPartialCaveatInfoOrBuilder();

    /**
     * <pre>
     * debug_trace is the debugging trace of this check, if requested.
     * </pre>
     *
     * <code>.authzed.api.v1.DebugInformation debug_trace = 4;</code>
     *
     * @return Whether the debugTrace field is set.
     */
    boolean hasDebugTrace();

    /**
     * <pre>
     * debug_trace is the debugging trace of this check, if requested.
     * </pre>
     *
     * <code>.authzed.api.v1.DebugInformation debug_trace = 4;</code>
     *
     * @return The debugTrace.
     */
    com.authzed.api.v1.DebugInformation getDebugTrace();

    /**
     * <pre>
     * debug_trace is the debugging trace of this check, if requested.
     * </pre>
     *
     * <code>.authzed.api.v1.DebugInformation debug_trace = 4;</code>
     */
    com.authzed.api.v1.DebugInformationOrBuilder getDebugTraceOrBuilder();

    /**
     * <pre>
     * optional_expires_at is the time at which at least one of the relationships used to
     * compute this result, expires (if any). This is *not* related to the caching window.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     *
     * @return Whether the optionalExpiresAt field is set.
     */
    boolean hasOptionalExpiresAt();

    /**
     * <pre>
     * optional_expires_at is the time at which at least one of the relationships used to
     * compute this result, expires (if any). This is *not* related to the caching window.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     *
     * @return The optionalExpiresAt.
     */
    com.google.protobuf.Timestamp getOptionalExpiresAt();

    /**
     * <pre>
     * optional_expires_at is the time at which at least one of the relationships used to
     * compute this result, expires (if any). This is *not* related to the caching window.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getOptionalExpiresAtOrBuilder();
}
