// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/debug.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface DebugInformationOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.DebugInformation)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * check holds debug information about a check request.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckDebugTrace check = 1;</code>
     *
     * @return Whether the check field is set.
     */
    boolean hasCheck();

    /**
     * <pre>
     * check holds debug information about a check request.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckDebugTrace check = 1;</code>
     *
     * @return The check.
     */
    com.authzed.api.v1.CheckDebugTrace getCheck();

    /**
     * <pre>
     * check holds debug information about a check request.
     * </pre>
     *
     * <code>.authzed.api.v1.CheckDebugTrace check = 1;</code>
     */
    com.authzed.api.v1.CheckDebugTraceOrBuilder getCheckOrBuilder();

    /**
     * <pre>
     * schema_used holds the schema used for the request.
     * </pre>
     *
     * <code>string schema_used = 2;</code>
     *
     * @return The schemaUsed.
     */
    java.lang.String getSchemaUsed();

    /**
     * <pre>
     * schema_used holds the schema used for the request.
     * </pre>
     *
     * <code>string schema_used = 2;</code>
     *
     * @return The bytes for schemaUsed.
     */
    com.google.protobuf.ByteString getSchemaUsedBytes();
}
