// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface DiffSchemaResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.DiffSchemaResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .authzed.api.v1.ReflectionSchemaDiff diffs = 1;</code>
     */
    java.util.List<com.authzed.api.v1.ReflectionSchemaDiff> getDiffsList();

    /**
     * <code>repeated .authzed.api.v1.ReflectionSchemaDiff diffs = 1;</code>
     */
    com.authzed.api.v1.ReflectionSchemaDiff getDiffs(int index);

    /**
     * <code>repeated .authzed.api.v1.ReflectionSchemaDiff diffs = 1;</code>
     */
    int getDiffsCount();

    /**
     * <code>repeated .authzed.api.v1.ReflectionSchemaDiff diffs = 1;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ReflectionSchemaDiffOrBuilder> getDiffsOrBuilderList();

    /**
     * <code>repeated .authzed.api.v1.ReflectionSchemaDiff diffs = 1;</code>
     */
    com.authzed.api.v1.ReflectionSchemaDiffOrBuilder getDiffsOrBuilder(int index);

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 2;</code>
     *
     * @return Whether the readAt field is set.
     */
    boolean hasReadAt();

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 2;</code>
     *
     * @return The readAt.
     */
    com.authzed.api.v1.ZedToken getReadAt();

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 2;</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getReadAtOrBuilder();
}
