// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExpDefinitionOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExpDefinition)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <pre>
     * comment is a human-readable comments on the definition. Will include
     * delimiter characters.
     * </pre>
     *
     * <code>string comment = 2;</code>
     *
     * @return The comment.
     */
    java.lang.String getComment();

    /**
     * <pre>
     * comment is a human-readable comments on the definition. Will include
     * delimiter characters.
     * </pre>
     *
     * <code>string comment = 2;</code>
     *
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString getCommentBytes();

    /**
     * <code>repeated .authzed.api.v1.ExpRelation relations = 3;</code>
     */
    java.util.List<com.authzed.api.v1.ExpRelation> getRelationsList();

    /**
     * <code>repeated .authzed.api.v1.ExpRelation relations = 3;</code>
     */
    com.authzed.api.v1.ExpRelation getRelations(int index);

    /**
     * <code>repeated .authzed.api.v1.ExpRelation relations = 3;</code>
     */
    int getRelationsCount();

    /**
     * <code>repeated .authzed.api.v1.ExpRelation relations = 3;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ExpRelationOrBuilder> getRelationsOrBuilderList();

    /**
     * <code>repeated .authzed.api.v1.ExpRelation relations = 3;</code>
     */
    com.authzed.api.v1.ExpRelationOrBuilder getRelationsOrBuilder(int index);

    /**
     * <code>repeated .authzed.api.v1.ExpPermission permissions = 4;</code>
     */
    java.util.List<com.authzed.api.v1.ExpPermission> getPermissionsList();

    /**
     * <code>repeated .authzed.api.v1.ExpPermission permissions = 4;</code>
     */
    com.authzed.api.v1.ExpPermission getPermissions(int index);

    /**
     * <code>repeated .authzed.api.v1.ExpPermission permissions = 4;</code>
     */
    int getPermissionsCount();

    /**
     * <code>repeated .authzed.api.v1.ExpPermission permissions = 4;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ExpPermissionOrBuilder> getPermissionsOrBuilderList();

    /**
     * <code>repeated .authzed.api.v1.ExpPermission permissions = 4;</code>
     */
    com.authzed.api.v1.ExpPermissionOrBuilder getPermissionsOrBuilder(int index);
}
