// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExperimentalUnregisterRelationshipCounterRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExperimentalUnregisterRelationshipCounterRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * name is the name of the counter being unregistered.
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <pre>
     * name is the name of the counter being unregistered.
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();
}
