// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExperimentalDiffSchemaRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExperimentalDiffSchemaRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return Whether the consistency field is set.
     */
    boolean hasConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return The consistency.
     */
    com.authzed.api.v1.Consistency getConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder();

    /**
     * <code>string comparison_schema = 2;</code>
     *
     * @return The comparisonSchema.
     */
    java.lang.String getComparisonSchema();

    /**
     * <code>string comparison_schema = 2;</code>
     *
     * @return The bytes for comparisonSchema.
     */
    com.google.protobuf.ByteString getComparisonSchemaBytes();
}
