// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExperimentalCountRelationshipsResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExperimentalCountRelationshipsResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * counter_still_calculating is true if the counter is still calculating the count.
     * </pre>
     *
     * <code>bool counter_still_calculating = 1;</code>
     *
     * @return Whether the counterStillCalculating field is set.
     */
    boolean hasCounterStillCalculating();

    /**
     * <pre>
     * counter_still_calculating is true if the counter is still calculating the count.
     * </pre>
     *
     * <code>bool counter_still_calculating = 1;</code>
     *
     * @return The counterStillCalculating.
     */
    boolean getCounterStillCalculating();

    /**
     * <pre>
     * read_counter_value is the value of the counter at the time of the read.
     * </pre>
     *
     * <code>.authzed.api.v1.ReadCounterValue read_counter_value = 2;</code>
     *
     * @return Whether the readCounterValue field is set.
     */
    boolean hasReadCounterValue();

    /**
     * <pre>
     * read_counter_value is the value of the counter at the time of the read.
     * </pre>
     *
     * <code>.authzed.api.v1.ReadCounterValue read_counter_value = 2;</code>
     *
     * @return The readCounterValue.
     */
    com.authzed.api.v1.ReadCounterValue getReadCounterValue();

    /**
     * <pre>
     * read_counter_value is the value of the counter at the time of the read.
     * </pre>
     *
     * <code>.authzed.api.v1.ReadCounterValue read_counter_value = 2;</code>
     */
    com.authzed.api.v1.ReadCounterValueOrBuilder getReadCounterValueOrBuilder();

    com.authzed.api.v1.ExperimentalCountRelationshipsResponse.CounterResultCase getCounterResultCase();
}
