// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/experimental_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExperimentalReflectSchemaRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExperimentalReflectSchemaRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return Whether the consistency field is set.
     */
    boolean hasConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return The consistency.
     */
    com.authzed.api.v1.Consistency getConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder();

    /**
     * <pre>
     * optional_filters defines optional filters that are applied in
     * an OR fashion to the schema, before being returned
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ExpSchemaFilter optional_filters = 2;</code>
     */
    java.util.List<com.authzed.api.v1.ExpSchemaFilter> getOptionalFiltersList();

    /**
     * <pre>
     * optional_filters defines optional filters that are applied in
     * an OR fashion to the schema, before being returned
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ExpSchemaFilter optional_filters = 2;</code>
     */
    com.authzed.api.v1.ExpSchemaFilter getOptionalFilters(int index);

    /**
     * <pre>
     * optional_filters defines optional filters that are applied in
     * an OR fashion to the schema, before being returned
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ExpSchemaFilter optional_filters = 2;</code>
     */
    int getOptionalFiltersCount();

    /**
     * <pre>
     * optional_filters defines optional filters that are applied in
     * an OR fashion to the schema, before being returned
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ExpSchemaFilter optional_filters = 2;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ExpSchemaFilterOrBuilder> getOptionalFiltersOrBuilderList();

    /**
     * <pre>
     * optional_filters defines optional filters that are applied in
     * an OR fashion to the schema, before being returned
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ExpSchemaFilter optional_filters = 2;</code>
     */
    com.authzed.api.v1.ExpSchemaFilterOrBuilder getOptionalFiltersOrBuilder(int index);
}
