// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/permission_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ExportBulkRelationshipsRequestOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ExportBulkRelationshipsRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return Whether the consistency field is set.
     */
    boolean hasConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return The consistency.
     */
    com.authzed.api.v1.Consistency getConsistency();

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder();

    /**
     * <pre>
     * optional_limit, if non-zero, specifies the limit on the number of
     * relationships the server can return in one page. By default, the server
     * will pick a page size, and the server is free to choose a smaller size
     * at will.
     * </pre>
     *
     * <code>uint32 optional_limit = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The optionalLimit.
     */
    int getOptionalLimit();

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results
     * should resume being returned. The cursor can be found on the
     * BulkExportRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 3;</code>
     *
     * @return Whether the optionalCursor field is set.
     */
    boolean hasOptionalCursor();

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results
     * should resume being returned. The cursor can be found on the
     * BulkExportRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 3;</code>
     *
     * @return The optionalCursor.
     */
    com.authzed.api.v1.Cursor getOptionalCursor();

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results
     * should resume being returned. The cursor can be found on the
     * BulkExportRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 3;</code>
     */
    com.authzed.api.v1.CursorOrBuilder getOptionalCursorOrBuilder();

    /**
     * <pre>
     * optional_relationship_filter, if specified, indicates the
     * filter to apply to each relationship to be exported.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter optional_relationship_filter = 4;</code>
     *
     * @return Whether the optionalRelationshipFilter field is set.
     */
    boolean hasOptionalRelationshipFilter();

    /**
     * <pre>
     * optional_relationship_filter, if specified, indicates the
     * filter to apply to each relationship to be exported.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter optional_relationship_filter = 4;</code>
     *
     * @return The optionalRelationshipFilter.
     */
    com.authzed.api.v1.RelationshipFilter getOptionalRelationshipFilter();

    /**
     * <pre>
     * optional_relationship_filter, if specified, indicates the
     * filter to apply to each relationship to be exported.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter optional_relationship_filter = 4;</code>
     */
    com.authzed.api.v1.RelationshipFilterOrBuilder getOptionalRelationshipFilterOrBuilder();
}
