// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/permission_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * <pre>
 * ImportBulkRelationshipsResponse is returned on successful completion of the
 * bulk load stream, and contains the total number of relationships loaded.
 * </pre>
 *
 * Protobuf type {@code authzed.api.v1.ImportBulkRelationshipsResponse}
 */
@com.google.protobuf.Generated
public final class ImportBulkRelationshipsResponse extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.ImportBulkRelationshipsResponse)
        ImportBulkRelationshipsResponseOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", ImportBulkRelationshipsResponse.class.getName());
    }

    // Use ImportBulkRelationshipsResponse.newBuilder() to construct.
    private ImportBulkRelationshipsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ImportBulkRelationshipsResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.ImportBulkRelationshipsResponse.class,
                        com.authzed.api.v1.ImportBulkRelationshipsResponse.Builder.class);
    }

    public static final int NUM_LOADED_FIELD_NUMBER = 1;

    private long numLoaded_ = 0L;

    /**
     * <code>uint64 num_loaded = 1;</code>
     *
     * @return The numLoaded.
     */
    @java.lang.Override
    public long getNumLoaded() {
        return numLoaded_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (numLoaded_ != 0L) {
            output.writeUInt64(1, numLoaded_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (numLoaded_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeUInt64Size(1, numLoaded_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.ImportBulkRelationshipsResponse)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.ImportBulkRelationshipsResponse other = (com.authzed.api.v1.ImportBulkRelationshipsResponse) obj;
        if (getNumLoaded() != other.getNumLoaded())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUM_LOADED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getNumLoaded());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.ImportBulkRelationshipsResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * ImportBulkRelationshipsResponse is returned on successful completion of the
     * bulk load stream, and contains the total number of relationships loaded.
     * </pre>
     *
     * Protobuf type {@code authzed.api.v1.ImportBulkRelationshipsResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.ImportBulkRelationshipsResponse)
            com.authzed.api.v1.ImportBulkRelationshipsResponseOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.ImportBulkRelationshipsResponse.class,
                            com.authzed.api.v1.ImportBulkRelationshipsResponse.Builder.class);
        }

        // Construct using com.authzed.api.v1.ImportBulkRelationshipsResponse.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            numLoaded_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.ImportBulkRelationshipsResponse getDefaultInstanceForType() {
            return com.authzed.api.v1.ImportBulkRelationshipsResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.ImportBulkRelationshipsResponse build() {
            com.authzed.api.v1.ImportBulkRelationshipsResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.ImportBulkRelationshipsResponse buildPartial() {
            com.authzed.api.v1.ImportBulkRelationshipsResponse result = new com.authzed.api.v1.ImportBulkRelationshipsResponse(
                    this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.authzed.api.v1.ImportBulkRelationshipsResponse result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.numLoaded_ = numLoaded_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.ImportBulkRelationshipsResponse) {
                return mergeFrom((com.authzed.api.v1.ImportBulkRelationshipsResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.ImportBulkRelationshipsResponse other) {
            if (other == com.authzed.api.v1.ImportBulkRelationshipsResponse.getDefaultInstance())
                return this;
            if (other.getNumLoaded() != 0L) {
                setNumLoaded(other.getNumLoaded());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            numLoaded_ = input.readUInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 8
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private long numLoaded_;

        /**
         * <code>uint64 num_loaded = 1;</code>
         *
         * @return The numLoaded.
         */
        @java.lang.Override
        public long getNumLoaded() {
            return numLoaded_;
        }

        /**
         * <code>uint64 num_loaded = 1;</code>
         *
         * @param value The numLoaded to set.
         * @return This builder for chaining.
         */
        public Builder setNumLoaded(long value) {
            numLoaded_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>uint64 num_loaded = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNumLoaded() {
            bitField0_ = (bitField0_ & ~0x00000001);
            numLoaded_ = 0L;
            onChanged();
            return this;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.ImportBulkRelationshipsResponse)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.ImportBulkRelationshipsResponse)
    private static final com.authzed.api.v1.ImportBulkRelationshipsResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.ImportBulkRelationshipsResponse();
    }

    public static com.authzed.api.v1.ImportBulkRelationshipsResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImportBulkRelationshipsResponse> PARSER = new com.google.protobuf.AbstractParser<ImportBulkRelationshipsResponse>() {

        @java.lang.Override
        public ImportBulkRelationshipsResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ImportBulkRelationshipsResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImportBulkRelationshipsResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.ImportBulkRelationshipsResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
