// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/permission_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public final class PermissionService extends com.google.protobuf.GeneratedFile {

    private PermissionService() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", PermissionService.class.getName());
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_Consistency_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_Consistency_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_RelationshipFilter_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_RelationshipFilter_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_SubjectFilter_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_SubjectFilter_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_SubjectFilter_RelationFilter_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_SubjectFilter_RelationFilter_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ReadRelationshipsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ReadRelationshipsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ReadRelationshipsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_Precondition_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_Precondition_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_WriteRelationshipsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_WriteRelationshipsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_WriteRelationshipsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_WriteRelationshipsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_DeleteRelationshipsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_DeleteRelationshipsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_DeleteRelationshipsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_DeleteRelationshipsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckPermissionRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckPermissionRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckPermissionResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckPermissionResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckBulkPermissionsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckBulkPermissionsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckBulkPermissionsRequestItem_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckBulkPermissionsRequestItem_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckBulkPermissionsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckBulkPermissionsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckBulkPermissionsPair_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckBulkPermissionsPair_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_CheckBulkPermissionsResponseItem_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_CheckBulkPermissionsResponseItem_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ExpandPermissionTreeRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ExpandPermissionTreeRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ExpandPermissionTreeResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ExpandPermissionTreeResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_LookupResourcesRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_LookupResourcesRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_LookupResourcesResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_LookupResourcesResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_LookupSubjectsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_LookupSubjectsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_LookupSubjectsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_LookupSubjectsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ResolvedSubject_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ResolvedSubject_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ImportBulkRelationshipsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ImportBulkRelationshipsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ExportBulkRelationshipsRequest_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ExportBulkRelationshipsRequest_fieldAccessorTable;

    static final com.google.protobuf.Descriptors.Descriptor internal_static_authzed_api_v1_ExportBulkRelationshipsResponse_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_authzed_api_v1_ExportBulkRelationshipsResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\'authzed/api/v1/permission_service.prot"
                + "o\022\016authzed.api.v1\032\031authzed/api/v1/core.p"
                + "roto\032\032authzed/api/v1/debug.proto\032\033buf/va" + "lidate/validate.proto\032\034google/api/annota"
                + "tions.proto\032\034google/protobuf/struct.prot" + "o\032\037google/protobuf/timestamp.proto\032\027goog"
                + "le/rpc/status.proto\032.protoc-gen-openapiv" + "2/options/annotations.proto\032\027validate/va"
                + "lidate.proto\"\354\001\n\013Consistency\022*\n\020minimize"
                + "_latency\030\001 \001(\010B\016\372B\004j\002\010\001\272H\004j\002\010\001H\000\0225\n\021at_l"
                + "east_as_fresh\030\002 \001(\0132\030.authzed.api.v1.Zed"
                + "TokenH\000\0225\n\021at_exact_snapshot\030\003 \001(\0132\030.aut"
                + "hzed.api.v1.ZedTokenH\000\022*\n\020fully_consiste"
                + "nt\030\004 \001(\010B\016\372B\004j\002\010\001\272H\004j\002\010\001H\000B\027\n\013requiremen"
                + "t\022\010\370B\001\272H\002\010\001\"\321\004\n\022RelationshipFilter\022\256\001\n\rr"
                + "esource_type\030\001 \001(\tB\226\001\372BHrF(\200\0012A^(([a-z]["
                + "a-z0-9_]{1,61}[a-z0-9]/)*[a-z][a-z0-9_]{" + "1,62}[a-z0-9])?$\272HHrF(\200\0012A^(([a-z][a-z0-"
                + "9_]{1,61}[a-z0-9]/)*[a-z][a-z0-9_]{1,62}" + "[a-z0-9])?$\022h\n\024optional_resource_id\030\002 \001("
                + "\tBJ\372B\"r (\200\0102\033^([a-zA-Z0-9/_|\\-=+]{1,})?$"
                + "\272H\"r (\200\0102\033^([a-zA-Z0-9/_|\\-=+]{1,})?$\022o\n"
                + "\033optional_resource_id_prefix\030\005 \001(\tBJ\372B\"r"
                + " (\200\0102\033^([a-zA-Z0-9/_|\\-=+]{1,})?$\272H\"r (\200"
                + "\0102\033^([a-zA-Z0-9/_|\\-=+]{1,})?$\022o\n\021option"
                + "al_relation\030\003 \001(\tBT\372B\'r%(@2!^([a-z][a-z0" + "-9_]{1,62}[a-z0-9])?$\272H\'r%(@2!^([a-z][a-"
                + "z0-9_]{1,62}[a-z0-9])?$\022>\n\027optional_subj" + "ect_filter\030\004 \001(\0132\035.authzed.api.v1.Subjec"
                + "tFilter\"\357\003\n\rSubjectFilter\022\247\001\n\014subject_ty"
                + "pe\030\001 \001(\tB\220\001\372BErC(\200\0012>^([a-z][a-z0-9_]{1,"
                + "61}[a-z0-9]/)*[a-z][a-z0-9_]{1,62}[a-z0-" + "9]$\272HErC(\200\0012>^([a-z][a-z0-9_]{1,61}[a-z0"
                + "-9]/)*[a-z][a-z0-9_]{1,62}[a-z0-9]$\022q\n\023o"
                + "ptional_subject_id\030\002 \001(\tBT\372B\'r%(\200\0102 ^((["
                + "a-zA-Z0-9/_|\\-=+]{1,})|\\*)?$\272H\'r%(\200\0102 ^(" + "([a-zA-Z0-9/_|\\-=+]{1,})|\\*)?$\022G\n\021option"
                + "al_relation\030\003 \001(\0132,.authzed.api.v1.Subje" + "ctFilter.RelationFilter\032x\n\016RelationFilte"
                + "r\022f\n\010relation\030\001 \001(\tBT\372B\'r%(@2!^([a-z][a-"
                + "z0-9_]{1,62}[a-z0-9])?$\272H\'r%(@2!^([a-z][" + "a-z0-9_]{1,62}[a-z0-9])?$\"\366\001\n\030ReadRelati"
                + "onshipsRequest\0220\n\013consistency\030\001 \001(\0132\033.au"
                + "thzed.api.v1.Consistency\022O\n\023relationship" + "_filter\030\002 \001(\0132\".authzed.api.v1.Relations"
                + "hipFilterB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\022&\n\016optional_li"
                + "mit\030\003 \001(\rB\016\372B\004*\002(\000\272H\004*\002(\000\022/\n\017optional_cu"
                + "rsor\030\004 \001(\0132\026.authzed.api.v1.Cursor\"\317\001\n\031R"
                + "eadRelationshipsResponse\0229\n\007read_at\030\001 \001("
                + "\0132\030.authzed.api.v1.ZedTokenB\016\372B\005\212\001\002\020\001\272H\003"
                + "\310\001\001\022B\n\014relationship\030\002 \001(\0132\034.authzed.api."
                + "v1.RelationshipB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\0223\n\023after"
                + "_result_cursor\030\003 \001(\0132\026.authzed.api.v1.Cu"
                + "rsor\"\203\002\n\014Precondition\022O\n\toperation\030\001 \001(\016"
                + "2&.authzed.api.v1.Precondition.Operation"
                + "B\024\372B\007\202\001\004\020\001 \000\272H\007\202\001\004\020\001 \000\022B\n\006filter\030\002 \001(\0132\""
                + ".authzed.api.v1.RelationshipFilterB\016\372B\005\212"
                + "\001\002\020\001\272H\003\310\001\001\"^\n\tOperation\022\031\n\025OPERATION_UNS"
                + "PECIFIED\020\000\022\034\n\030OPERATION_MUST_NOT_MATCH\020\001"
                + "\022\030\n\024OPERATION_MUST_MATCH\020\002\"\222\002\n\031WriteRela"
                + "tionshipsRequest\022M\n\007updates\030\001 \003(\0132\".auth"
                + "zed.api.v1.RelationshipUpdateB\030\372B\n\222\001\007\"\005\212"
                + "\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\022V\n\026optional_precondition"
                + "s\030\002 \003(\0132\034.authzed.api.v1.PreconditionB\030\372"
                + "B\n\222\001\007\"\005\212\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\022N\n\035optional_tran"
                + "saction_metadata\030\003 \001(\0132\027.google.protobuf"
                + ".StructB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\"J\n\032WriteRelation"
                + "shipsResponse\022,\n\nwritten_at\030\001 \001(\0132\030.auth"
                + "zed.api.v1.ZedToken\"\347\002\n\032DeleteRelationsh"
                + "ipsRequest\022O\n\023relationship_filter\030\001 \001(\0132"
                + "\".authzed.api.v1.RelationshipFilterB\016\372B\005"
                + "\212\001\002\020\001\272H\003\310\001\001\022V\n\026optional_preconditions\030\002 "
                + "\003(\0132\034.authzed.api.v1.PreconditionB\030\372B\n\222\001"
                + "\007\"\005\212\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\022&\n\016optional_limit\030\003 "
                + "\001(\rB\016\372B\004*\002(\000\272H\004*\002(\000\022(\n optional_allow_pa"
                + "rtial_deletions\030\004 \001(\010\022N\n\035optional_transa"
                + "ction_metadata\030\005 \001(\0132\027.google.protobuf.S"
                + "tructB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\"\277\002\n\033DeleteRelation"
                + "shipsResponse\022,\n\ndeleted_at\030\001 \001(\0132\030.auth"
                + "zed.api.v1.ZedToken\022W\n\021deletion_progress" + "\030\002 \001(\0162<.authzed.api.v1.DeleteRelationsh"
                + "ipsResponse.DeletionProgress\022#\n\033relation"
                + "ships_deleted_count\030\003 \001(\004\"t\n\020DeletionPro"
                + "gress\022!\n\035DELETION_PROGRESS_UNSPECIFIED\020\000"
                + "\022\036\n\032DELETION_PROGRESS_COMPLETE\020\001\022\035\n\031DELE"
                + "TION_PROGRESS_PARTIAL\020\002\"\212\003\n\026CheckPermiss"
                + "ionRequest\0220\n\013consistency\030\001 \001(\0132\033.authze"
                + "d.api.v1.Consistency\022A\n\010resource\030\002 \001(\0132\037"
                + ".authzed.api.v1.ObjectReferenceB\016\372B\005\212\001\002\020"
                + "\001\272H\003\310\001\001\022h\n\npermission\030\003 \001(\tBT\372B\'r%(@2!^("
                + "[a-z][a-z0-9_]{1,62}[a-z0-9])?$\272H\'r%(@2!" + "^([a-z][a-z0-9_]{1,62}[a-z0-9])?$\022A\n\007sub"
                + "ject\030\004 \001(\0132 .authzed.api.v1.SubjectRefer"
                + "enceB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\0228\n\007context\030\005 \001(\0132\027."
                + "google.protobuf.StructB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\022\024"
                + "\n\014with_tracing\030\006 \001(\010\"\240\004\n\027CheckPermission"
                + "Response\022<\n\nchecked_at\030\001 \001(\0132\030.authzed.a"
                + "pi.v1.ZedTokenB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\022d\n\016permis"
                + "sionship\030\002 \001(\01626.authzed.api.v1.CheckPer"
                + "missionResponse.PermissionshipB\024\372B\007\202\001\004\020\001"
                + " \000\272H\007\202\001\004\020\001 \000\022N\n\023partial_caveat_info\030\003 \001("
                + "\0132!.authzed.api.v1.PartialCaveatInfoB\016\372B"
                + "\005\212\001\002\020\000\272H\003\310\001\000\0225\n\013debug_trace\030\004 \001(\0132 .auth"
                + "zed.api.v1.DebugInformation\0227\n\023optional_" + "expires_at\030\005 \001(\0132\032.google.protobuf.Times"
                + "tamp\"\240\001\n\016Permissionship\022\036\n\032PERMISSIONSHI"
                + "P_UNSPECIFIED\020\000\022 \n\034PERMISSIONSHIP_NO_PER"
                + "MISSION\020\001\022!\n\035PERMISSIONSHIP_HAS_PERMISSI" + "ON\020\002\022)\n%PERMISSIONSHIP_CONDITIONAL_PERMI"
                + "SSION\020\003\"\277\001\n\033CheckBulkPermissionsRequest\022"
                + "0\n\013consistency\030\001 \001(\0132\033.authzed.api.v1.Co"
                + "nsistency\022X\n\005items\030\002 \003(\0132/.authzed.api.v"
                + "1.CheckBulkPermissionsRequestItemB\030\372B\n\222\001"
                + "\007\"\005\212\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\022\024\n\014with_tracing\030\003 \001("
                + "\010\"\313\002\n\037CheckBulkPermissionsRequestItem\022A\n"
                + "\010resource\030\001 \001(\0132\037.authzed.api.v1.ObjectR"
                + "eferenceB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\022h\n\npermission\030\002"
                + " \001(\tBT\372B\'r%(@2!^([a-z][a-z0-9_]{1,62}[a-" + "z0-9])?$\272H\'r%(@2!^([a-z][a-z0-9_]{1,62}["
                + "a-z0-9])?$\022A\n\007subject\030\003 \001(\0132 .authzed.ap"
                + "i.v1.SubjectReferenceB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\0228\n"
                + "\007context\030\004 \001(\0132\027.google.protobuf.StructB"
                + "\016\372B\005\212\001\002\020\000\272H\003\310\001\000\"\257\001\n\034CheckBulkPermissions"
                + "Response\022<\n\nchecked_at\030\001 \001(\0132\030.authzed.a"
                + "pi.v1.ZedTokenB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\022Q\n\005pairs\030"
                + "\002 \003(\0132(.authzed.api.v1.CheckBulkPermissi"
                + "onsPairB\030\372B\n\222\001\007\"\005\212\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\"\317\001\n\030Ch"
                + "eckBulkPermissionsPair\022@\n\007request\030\001 \001(\0132" + "/.authzed.api.v1.CheckBulkPermissionsReq"
                + "uestItem\022@\n\004item\030\002 \001(\01320.authzed.api.v1."
                + "CheckBulkPermissionsResponseItemH\000\022#\n\005er"
                + "ror\030\003 \001(\0132\022.google.rpc.StatusH\000B\n\n\010respo"
                + "nse\"\217\002\n CheckBulkPermissionsResponseItem"
                + "\022d\n\016permissionship\030\001 \001(\01626.authzed.api.v" + "1.CheckPermissionResponse.Permissionship"
                + "B\024\372B\007\202\001\004\020\001 \000\272H\007\202\001\004\020\001 \000\022N\n\023partial_caveat"
                + "_info\030\002 \001(\0132!.authzed.api.v1.PartialCave"
                + "atInfoB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\0225\n\013debug_trace\030\003 "
                + "\001(\0132 .authzed.api.v1.DebugInformation\"\374\001"
                + "\n\033ExpandPermissionTreeRequest\0220\n\013consist"
                + "ency\030\001 \001(\0132\033.authzed.api.v1.Consistency\022"
                + "A\n\010resource\030\002 \001(\0132\037.authzed.api.v1.Objec"
                + "tReferenceB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\022h\n\npermission"
                + "\030\003 \001(\tBT\372B\'r%(@2!^([a-z][a-z0-9_]{1,62}[" + "a-z0-9])?$\272H\'r%(@2!^([a-z][a-z0-9_]{1,62"
                + "}[a-z0-9])?$\"\214\001\n\034ExpandPermissionTreeRes"
                + "ponse\022-\n\013expanded_at\030\001 \001(\0132\030.authzed.api"
                + ".v1.ZedToken\022=\n\ttree_root\030\002 \001(\0132*.authze"
                + "d.api.v1.PermissionRelationshipTree\"\266\004\n\026"
                + "LookupResourcesRequest\0220\n\013consistency\030\001 "
                + "\001(\0132\033.authzed.api.v1.Consistency\022\257\001\n\024res"
                + "ource_object_type\030\002 \001(\tB\220\001\372BErC(\200\0012>^([a"
                + "-z][a-z0-9_]{1,61}[a-z0-9]/)*[a-z][a-z0-" + "9_]{1,62}[a-z0-9]$\272HErC(\200\0012>^([a-z][a-z0"
                + "-9_]{1,61}[a-z0-9]/)*[a-z][a-z0-9_]{1,62" + "}[a-z0-9]$\022b\n\npermission\030\003 \001(\tBN\372B$r\"(@2"
                + "\036^[a-z][a-z0-9_]{1,62}[a-z0-9]$\272H$r\"(@2\036" + "^[a-z][a-z0-9_]{1,62}[a-z0-9]$\022A\n\007subjec"
                + "t\030\004 \001(\0132 .authzed.api.v1.SubjectReferenc"
                + "eB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\0228\n\007context\030\005 \001(\0132\027.goo"
                + "gle.protobuf.StructB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\022&\n\016o"
                + "ptional_limit\030\006 \001(\rB\016\372B\004*\002(\000\272H\004*\002(\000\022/\n\017o"
                + "ptional_cursor\030\007 \001(\0132\026.authzed.api.v1.Cu"
                + "rsor\"\276\002\n\027LookupResourcesResponse\022.\n\014look"
                + "ed_up_at\030\001 \001(\0132\030.authzed.api.v1.ZedToken"
                + "\022\032\n\022resource_object_id\030\002 \001(\t\022R\n\016permissi"
                + "onship\030\003 \001(\0162$.authzed.api.v1.LookupPerm"
                + "issionshipB\024\372B\007\202\001\004\020\001 \000\272H\007\202\001\004\020\001 \000\022N\n\023part"
                + "ial_caveat_info\030\004 \001(\0132!.authzed.api.v1.P"
                + "artialCaveatInfoB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\0223\n\023afte"
                + "r_result_cursor\030\005 \001(\0132\026.authzed.api.v1.C"
                + "ursor\"\214\007\n\025LookupSubjectsRequest\0220\n\013consi"
                + "stency\030\001 \001(\0132\033.authzed.api.v1.Consistenc"
                + "y\022A\n\010resource\030\002 \001(\0132\037.authzed.api.v1.Obj"
                + "ectReferenceB\016\372B\005\212\001\002\020\001\272H\003\310\001\001\022h\n\npermissi"
                + "on\030\003 \001(\tBT\372B\'r%(@2!^([a-z][a-z0-9_]{1,62" + "}[a-z0-9])?$\272H\'r%(@2!^([a-z][a-z0-9_]{1,"
                + "62}[a-z0-9])?$\022\256\001\n\023subject_object_type\030\004"
                + " \001(\tB\220\001\372BErC(\200\0012>^([a-z][a-z0-9_]{1,61}[" + "a-z0-9]/)*[a-z][a-z0-9_]{1,62}[a-z0-9]$\272"
                + "HErC(\200\0012>^([a-z][a-z0-9_]{1,61}[a-z0-9]/" + ")*[a-z][a-z0-9_]{1,62}[a-z0-9]$\022w\n\031optio"
                + "nal_subject_relation\030\005 \001(\tBT\372B\'r%(@2!^([" + "a-z][a-z0-9_]{1,62}[a-z0-9])?$\272H\'r%(@2!^"
                + "([a-z][a-z0-9_]{1,62}[a-z0-9])?$\0228\n\007cont"
                + "ext\030\006 \001(\0132\027.google.protobuf.StructB\016\372B\005\212"
                + "\001\002\020\000\272H\003\310\001\000\022/\n\027optional_concrete_limit\030\007 "
                + "\001(\rB\016\372B\004*\002(\000\272H\004*\002(\000\022/\n\017optional_cursor\030\010"
                + " \001(\0132\026.authzed.api.v1.Cursor\022M\n\017wildcard"
                + "_option\030\t \001(\01624.authzed.api.v1.LookupSub" + "jectsRequest.WildcardOption\"\177\n\016WildcardO"
                + "ption\022\037\n\033WILDCARD_OPTION_UNSPECIFIED\020\000\022%"
                + "\n!WILDCARD_OPTION_INCLUDE_WILDCARDS\020\001\022%\n"
                + "!WILDCARD_OPTION_EXCLUDE_WILDCARDS\020\002\"\324\003\n"
                + "\026LookupSubjectsResponse\022.\n\014looked_up_at\030"
                + "\001 \001(\0132\030.authzed.api.v1.ZedToken\022\035\n\021subje"
                + "ct_object_id\030\002 \001(\tB\002\030\001\022 \n\024excluded_subje"
                + "ct_ids\030\003 \003(\tB\002\030\001\022T\n\016permissionship\030\004 \001(\016"
                + "2$.authzed.api.v1.LookupPermissionshipB\026"
                + "\030\001\372B\007\202\001\004\020\001 \000\272H\007\202\001\004\020\001 \000\022P\n\023partial_caveat"
                + "_info\030\005 \001(\0132!.authzed.api.v1.PartialCave"
                + "atInfoB\020\030\001\372B\005\212\001\002\020\000\272H\003\310\001\000\0220\n\007subject\030\006 \001("
                + "\0132\037.authzed.api.v1.ResolvedSubject\022:\n\021ex"
                + "cluded_subjects\030\007 \003(\0132\037.authzed.api.v1.R"
                + "esolvedSubject\0223\n\023after_result_cursor\030\010 "
                + "\001(\0132\026.authzed.api.v1.Cursor\"\320\001\n\017Resolved"
                + "Subject\022\031\n\021subject_object_id\030\001 \001(\t\022R\n\016pe"
                + "rmissionship\030\002 \001(\0162$.authzed.api.v1.Look"
                + "upPermissionshipB\024\372B\007\202\001\004\020\001 \000\272H\007\202\001\004\020\001 \000\022N"
                + "\n\023partial_caveat_info\030\003 \001(\0132!.authzed.ap"
                + "i.v1.PartialCaveatInfoB\016\372B\005\212\001\002\020\000\272H\003\310\001\000\"o"
                + "\n\036ImportBulkRelationshipsRequest\022M\n\rrela"
                + "tionships\030\001 \003(\0132\034.authzed.api.v1.Relatio"
                + "nshipB\030\372B\n\222\001\007\"\005\212\001\002\020\001\272H\010\222\001\005\"\003\310\001\001\"5\n\037Impor"
                + "tBulkRelationshipsResponse\022\022\n\nnum_loaded"
                + "\030\001 \001(\004\"\365\001\n\036ExportBulkRelationshipsReques"
                + "t\0220\n\013consistency\030\001 \001(\0132\033.authzed.api.v1."
                + "Consistency\022&\n\016optional_limit\030\002 \001(\rB\016\372B\004"
                + "*\002(\000\272H\004*\002(\000\022/\n\017optional_cursor\030\003 \001(\0132\026.a"
                + "uthzed.api.v1.Cursor\022H\n\034optional_relatio" + "nship_filter\030\004 \001(\0132\".authzed.api.v1.Rela"
                + "tionshipFilter\"\213\001\n\037ExportBulkRelationshi"
                + "psResponse\0223\n\023after_result_cursor\030\001 \001(\0132"
                + "\026.authzed.api.v1.Cursor\0223\n\rrelationships"
                + "\030\002 \003(\0132\034.authzed.api.v1.Relationship*\231\001\n"
                + "\024LookupPermissionship\022%\n!LOOKUP_PERMISSI" + "ONSHIP_UNSPECIFIED\020\000\022(\n$LOOKUP_PERMISSIO"
                + "NSHIP_HAS_PERMISSION\020\001\0220\n,LOOKUP_PERMISS"
                + "IONSHIP_CONDITIONAL_PERMISSION\020\0022\212\r\n\022Per"
                + "missionsService\022\235\001\n\021ReadRelationships\022(." + "authzed.api.v1.ReadRelationshipsRequest\032"
                + ").authzed.api.v1.ReadRelationshipsRespon"
                + "se\"1\222A\r\n\013Permissions\202\323\344\223\002\033\"\026/v1/relation"
                + "ships/read:\001*0\001\022\237\001\n\022WriteRelationships\022)" + ".authzed.api.v1.WriteRelationshipsReques"
                + "t\032*.authzed.api.v1.WriteRelationshipsRes"
                + "ponse\"2\222A\r\n\013Permissions\202\323\344\223\002\034\"\027/v1/relat"
                + "ionships/write:\001*\022\243\001\n\023DeleteRelationship" + "s\022*.authzed.api.v1.DeleteRelationshipsRe"
                + "quest\032+.authzed.api.v1.DeleteRelationshi"
                + "psResponse\"3\222A\r\n\013Permissions\202\323\344\223\002\035\"\030/v1/"
                + "relationships/delete:\001*\022\224\001\n\017CheckPermiss" + "ion\022&.authzed.api.v1.CheckPermissionRequ"
                + "est\032\'.authzed.api.v1.CheckPermissionResp"
                + "onse\"0\222A\r\n\013Permissions\202\323\344\223\002\032\"\025/v1/permis"
                + "sions/check:\001*\022\247\001\n\024CheckBulkPermissions\022" + "+.authzed.api.v1.CheckBulkPermissionsReq"
                + "uest\032,.authzed.api.v1.CheckBulkPermissio"
                + "nsResponse\"4\222A\r\n\013Permissions\202\323\344\223\002\036\"\031/v1/"
                + "permissions/checkbulk:\001*\022\244\001\n\024ExpandPermi" + "ssionTree\022+.authzed.api.v1.ExpandPermiss"
                + "ionTreeRequest\032,.authzed.api.v1.ExpandPe" + "rmissionTreeResponse\"1\222A\r\n\013Permissions\202\323"
                + "\344\223\002\033\"\026/v1/permissions/expand:\001*\022\232\001\n\017Look"
                + "upResources\022&.authzed.api.v1.LookupResou" + "rcesRequest\032\'.authzed.api.v1.LookupResou"
                + "rcesResponse\"4\222A\r\n\013Permissions\202\323\344\223\002\036\"\031/v"
                + "1/permissions/resources:\001*0\001\022\226\001\n\016LookupS" + "ubjects\022%.authzed.api.v1.LookupSubjectsR"
                + "equest\032&.authzed.api.v1.LookupSubjectsRe"
                + "sponse\"3\222A\r\n\013Permissions\202\323\344\223\002\035\"\030/v1/perm"
                + "issions/subjects:\001*0\001\022\265\001\n\027ImportBulkRela" + "tionships\022..authzed.api.v1.ImportBulkRel"
                + "ationshipsRequest\032/.authzed.api.v1.Impor" + "tBulkRelationshipsResponse\"7\222A\r\n\013Permiss"
                + "ions\202\323\344\223\002!\"\034/v1/relationships/importbulk"
                + ":\001*(\001\022\265\001\n\027ExportBulkRelationships\022..auth" + "zed.api.v1.ExportBulkRelationshipsReques"
                + "t\032/.authzed.api.v1.ExportBulkRelationshi"
                + "psResponse\"7\222A\r\n\013Permissions\202\323\344\223\002!\"\034/v1/"
                + "relationships/exportbulk:\001*0\001BJ\n\022com.aut" + "hzed.api.v1P\001Z2github.com/authzed/authze"
                + "d-go/proto/authzed/api/v1b\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] { com.authzed.api.v1.Core.getDescriptor(),
                        com.authzed.api.v1.Debug.getDescriptor(), build.buf.validate.ValidateProto.getDescriptor(),
                        com.google.api.AnnotationsProto.getDescriptor(), com.google.protobuf.StructProto.getDescriptor(),
                        com.google.protobuf.TimestampProto.getDescriptor(), com.google.rpc.StatusProto.getDescriptor(),
                        grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor(),
                        io.envoyproxy.pgv.validate.Validate.getDescriptor() });
        internal_static_authzed_api_v1_Consistency_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_authzed_api_v1_Consistency_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_Consistency_descriptor, new java.lang.String[] { "MinimizeLatency",
                        "AtLeastAsFresh", "AtExactSnapshot", "FullyConsistent", "Requirement" });
        internal_static_authzed_api_v1_RelationshipFilter_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_authzed_api_v1_RelationshipFilter_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_RelationshipFilter_descriptor, new java.lang.String[] { "ResourceType",
                        "OptionalResourceId", "OptionalResourceIdPrefix", "OptionalRelation", "OptionalSubjectFilter" });
        internal_static_authzed_api_v1_SubjectFilter_descriptor = getDescriptor().getMessageTypes().get(2);
        internal_static_authzed_api_v1_SubjectFilter_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_SubjectFilter_descriptor,
                new java.lang.String[] { "SubjectType", "OptionalSubjectId", "OptionalRelation" });
        internal_static_authzed_api_v1_SubjectFilter_RelationFilter_descriptor = internal_static_authzed_api_v1_SubjectFilter_descriptor
                .getNestedTypes().get(0);
        internal_static_authzed_api_v1_SubjectFilter_RelationFilter_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_SubjectFilter_RelationFilter_descriptor, new java.lang.String[] { "Relation" });
        internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor = getDescriptor().getMessageTypes().get(3);
        internal_static_authzed_api_v1_ReadRelationshipsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor,
                new java.lang.String[] { "Consistency", "RelationshipFilter", "OptionalLimit", "OptionalCursor" });
        internal_static_authzed_api_v1_ReadRelationshipsResponse_descriptor = getDescriptor().getMessageTypes().get(4);
        internal_static_authzed_api_v1_ReadRelationshipsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ReadRelationshipsResponse_descriptor,
                new java.lang.String[] { "ReadAt", "Relationship", "AfterResultCursor" });
        internal_static_authzed_api_v1_Precondition_descriptor = getDescriptor().getMessageTypes().get(5);
        internal_static_authzed_api_v1_Precondition_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_Precondition_descriptor, new java.lang.String[] { "Operation", "Filter" });
        internal_static_authzed_api_v1_WriteRelationshipsRequest_descriptor = getDescriptor().getMessageTypes().get(6);
        internal_static_authzed_api_v1_WriteRelationshipsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_WriteRelationshipsRequest_descriptor,
                new java.lang.String[] { "Updates", "OptionalPreconditions", "OptionalTransactionMetadata" });
        internal_static_authzed_api_v1_WriteRelationshipsResponse_descriptor = getDescriptor().getMessageTypes().get(7);
        internal_static_authzed_api_v1_WriteRelationshipsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_WriteRelationshipsResponse_descriptor, new java.lang.String[] { "WrittenAt" });
        internal_static_authzed_api_v1_DeleteRelationshipsRequest_descriptor = getDescriptor().getMessageTypes().get(8);
        internal_static_authzed_api_v1_DeleteRelationshipsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_DeleteRelationshipsRequest_descriptor,
                new java.lang.String[] { "RelationshipFilter", "OptionalPreconditions", "OptionalLimit",
                        "OptionalAllowPartialDeletions", "OptionalTransactionMetadata" });
        internal_static_authzed_api_v1_DeleteRelationshipsResponse_descriptor = getDescriptor().getMessageTypes().get(9);
        internal_static_authzed_api_v1_DeleteRelationshipsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_DeleteRelationshipsResponse_descriptor,
                new java.lang.String[] { "DeletedAt", "DeletionProgress", "RelationshipsDeletedCount" });
        internal_static_authzed_api_v1_CheckPermissionRequest_descriptor = getDescriptor().getMessageTypes().get(10);
        internal_static_authzed_api_v1_CheckPermissionRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckPermissionRequest_descriptor,
                new java.lang.String[] { "Consistency", "Resource", "Permission", "Subject", "Context", "WithTracing" });
        internal_static_authzed_api_v1_CheckPermissionResponse_descriptor = getDescriptor().getMessageTypes().get(11);
        internal_static_authzed_api_v1_CheckPermissionResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckPermissionResponse_descriptor, new java.lang.String[] { "CheckedAt",
                        "Permissionship", "PartialCaveatInfo", "DebugTrace", "OptionalExpiresAt" });
        internal_static_authzed_api_v1_CheckBulkPermissionsRequest_descriptor = getDescriptor().getMessageTypes().get(12);
        internal_static_authzed_api_v1_CheckBulkPermissionsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckBulkPermissionsRequest_descriptor,
                new java.lang.String[] { "Consistency", "Items", "WithTracing" });
        internal_static_authzed_api_v1_CheckBulkPermissionsRequestItem_descriptor = getDescriptor().getMessageTypes().get(13);
        internal_static_authzed_api_v1_CheckBulkPermissionsRequestItem_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckBulkPermissionsRequestItem_descriptor,
                new java.lang.String[] { "Resource", "Permission", "Subject", "Context" });
        internal_static_authzed_api_v1_CheckBulkPermissionsResponse_descriptor = getDescriptor().getMessageTypes().get(14);
        internal_static_authzed_api_v1_CheckBulkPermissionsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckBulkPermissionsResponse_descriptor,
                new java.lang.String[] { "CheckedAt", "Pairs" });
        internal_static_authzed_api_v1_CheckBulkPermissionsPair_descriptor = getDescriptor().getMessageTypes().get(15);
        internal_static_authzed_api_v1_CheckBulkPermissionsPair_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckBulkPermissionsPair_descriptor,
                new java.lang.String[] { "Request", "Item", "Error", "Response" });
        internal_static_authzed_api_v1_CheckBulkPermissionsResponseItem_descriptor = getDescriptor().getMessageTypes().get(16);
        internal_static_authzed_api_v1_CheckBulkPermissionsResponseItem_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_CheckBulkPermissionsResponseItem_descriptor,
                new java.lang.String[] { "Permissionship", "PartialCaveatInfo", "DebugTrace" });
        internal_static_authzed_api_v1_ExpandPermissionTreeRequest_descriptor = getDescriptor().getMessageTypes().get(17);
        internal_static_authzed_api_v1_ExpandPermissionTreeRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ExpandPermissionTreeRequest_descriptor,
                new java.lang.String[] { "Consistency", "Resource", "Permission" });
        internal_static_authzed_api_v1_ExpandPermissionTreeResponse_descriptor = getDescriptor().getMessageTypes().get(18);
        internal_static_authzed_api_v1_ExpandPermissionTreeResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ExpandPermissionTreeResponse_descriptor,
                new java.lang.String[] { "ExpandedAt", "TreeRoot" });
        internal_static_authzed_api_v1_LookupResourcesRequest_descriptor = getDescriptor().getMessageTypes().get(19);
        internal_static_authzed_api_v1_LookupResourcesRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_LookupResourcesRequest_descriptor, new java.lang.String[] { "Consistency",
                        "ResourceObjectType", "Permission", "Subject", "Context", "OptionalLimit", "OptionalCursor" });
        internal_static_authzed_api_v1_LookupResourcesResponse_descriptor = getDescriptor().getMessageTypes().get(20);
        internal_static_authzed_api_v1_LookupResourcesResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_LookupResourcesResponse_descriptor, new java.lang.String[] { "LookedUpAt",
                        "ResourceObjectId", "Permissionship", "PartialCaveatInfo", "AfterResultCursor" });
        internal_static_authzed_api_v1_LookupSubjectsRequest_descriptor = getDescriptor().getMessageTypes().get(21);
        internal_static_authzed_api_v1_LookupSubjectsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_LookupSubjectsRequest_descriptor,
                new java.lang.String[] { "Consistency", "Resource", "Permission", "SubjectObjectType",
                        "OptionalSubjectRelation", "Context", "OptionalConcreteLimit", "OptionalCursor", "WildcardOption" });
        internal_static_authzed_api_v1_LookupSubjectsResponse_descriptor = getDescriptor().getMessageTypes().get(22);
        internal_static_authzed_api_v1_LookupSubjectsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_LookupSubjectsResponse_descriptor,
                new java.lang.String[] { "LookedUpAt", "SubjectObjectId", "ExcludedSubjectIds", "Permissionship",
                        "PartialCaveatInfo", "Subject", "ExcludedSubjects", "AfterResultCursor" });
        internal_static_authzed_api_v1_ResolvedSubject_descriptor = getDescriptor().getMessageTypes().get(23);
        internal_static_authzed_api_v1_ResolvedSubject_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ResolvedSubject_descriptor,
                new java.lang.String[] { "SubjectObjectId", "Permissionship", "PartialCaveatInfo" });
        internal_static_authzed_api_v1_ImportBulkRelationshipsRequest_descriptor = getDescriptor().getMessageTypes().get(24);
        internal_static_authzed_api_v1_ImportBulkRelationshipsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ImportBulkRelationshipsRequest_descriptor,
                new java.lang.String[] { "Relationships" });
        internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor = getDescriptor().getMessageTypes().get(25);
        internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ImportBulkRelationshipsResponse_descriptor,
                new java.lang.String[] { "NumLoaded" });
        internal_static_authzed_api_v1_ExportBulkRelationshipsRequest_descriptor = getDescriptor().getMessageTypes().get(26);
        internal_static_authzed_api_v1_ExportBulkRelationshipsRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ExportBulkRelationshipsRequest_descriptor,
                new java.lang.String[] { "Consistency", "OptionalLimit", "OptionalCursor", "OptionalRelationshipFilter" });
        internal_static_authzed_api_v1_ExportBulkRelationshipsResponse_descriptor = getDescriptor().getMessageTypes().get(27);
        internal_static_authzed_api_v1_ExportBulkRelationshipsResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_authzed_api_v1_ExportBulkRelationshipsResponse_descriptor,
                new java.lang.String[] { "AfterResultCursor", "Relationships" });
        descriptor.resolveAllFeaturesImmutable();
        com.authzed.api.v1.Core.getDescriptor();
        com.authzed.api.v1.Debug.getDescriptor();
        build.buf.validate.ValidateProto.getDescriptor();
        com.google.api.AnnotationsProto.getDescriptor();
        com.google.protobuf.StructProto.getDescriptor();
        com.google.protobuf.TimestampProto.getDescriptor();
        com.google.rpc.StatusProto.getDescriptor();
        grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor();
        io.envoyproxy.pgv.validate.Validate.getDescriptor();
        com.google.protobuf.ExtensionRegistry registry = com.google.protobuf.ExtensionRegistry.newInstance();
        registry.add(build.buf.validate.ValidateProto.field);
        registry.add(build.buf.validate.ValidateProto.oneof);
        registry.add(com.google.api.AnnotationsProto.http);
        registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Operation);
        registry.add(io.envoyproxy.pgv.validate.Validate.required);
        registry.add(io.envoyproxy.pgv.validate.Validate.rules);
        com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(descriptor, registry);
    }
    // @@protoc_insertion_point(outer_class_scope)
}
