// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/core.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface PermissionRelationshipTreeOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.PermissionRelationshipTree)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet intermediate = 1;</code>
     *
     * @return Whether the intermediate field is set.
     */
    boolean hasIntermediate();

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet intermediate = 1;</code>
     *
     * @return The intermediate.
     */
    com.authzed.api.v1.AlgebraicSubjectSet getIntermediate();

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet intermediate = 1;</code>
     */
    com.authzed.api.v1.AlgebraicSubjectSetOrBuilder getIntermediateOrBuilder();

    /**
     * <code>.authzed.api.v1.DirectSubjectSet leaf = 2;</code>
     *
     * @return Whether the leaf field is set.
     */
    boolean hasLeaf();

    /**
     * <code>.authzed.api.v1.DirectSubjectSet leaf = 2;</code>
     *
     * @return The leaf.
     */
    com.authzed.api.v1.DirectSubjectSet getLeaf();

    /**
     * <code>.authzed.api.v1.DirectSubjectSet leaf = 2;</code>
     */
    com.authzed.api.v1.DirectSubjectSetOrBuilder getLeafOrBuilder();

    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     *
     * @return Whether the expandedObject field is set.
     */
    boolean hasExpandedObject();

    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     *
     * @return The expandedObject.
     */
    com.authzed.api.v1.ObjectReference getExpandedObject();

    /**
     * <code>.authzed.api.v1.ObjectReference expanded_object = 3;</code>
     */
    com.authzed.api.v1.ObjectReferenceOrBuilder getExpandedObjectOrBuilder();

    /**
     * <code>string expanded_relation = 4;</code>
     *
     * @return The expandedRelation.
     */
    java.lang.String getExpandedRelation();

    /**
     * <code>string expanded_relation = 4;</code>
     *
     * @return The bytes for expandedRelation.
     */
    com.google.protobuf.ByteString getExpandedRelationBytes();

    com.authzed.api.v1.PermissionRelationshipTree.TreeTypeCase getTreeTypeCase();
}
