// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/permission_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * <pre>
 * ReadRelationshipsRequest specifies one or more filters used to read matching
 * relationships within the system.
 * </pre>
 *
 * Protobuf type {@code authzed.api.v1.ReadRelationshipsRequest}
 */
@com.google.protobuf.Generated
public final class ReadRelationshipsRequest extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.ReadRelationshipsRequest)
        ReadRelationshipsRequestOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", ReadRelationshipsRequest.class.getName());
    }

    // Use ReadRelationshipsRequest.newBuilder() to construct.
    private ReadRelationshipsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ReadRelationshipsRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ReadRelationshipsRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReadRelationshipsRequest.class,
                        com.authzed.api.v1.ReadRelationshipsRequest.Builder.class);
    }

    private int bitField0_;

    public static final int CONSISTENCY_FIELD_NUMBER = 1;

    private com.authzed.api.v1.Consistency consistency_;

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return Whether the consistency field is set.
     */
    @java.lang.Override
    public boolean hasConsistency() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     *
     * @return The consistency.
     */
    @java.lang.Override
    public com.authzed.api.v1.Consistency getConsistency() {
        return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
    }

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder() {
        return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
    }

    public static final int RELATIONSHIP_FILTER_FIELD_NUMBER = 2;

    private com.authzed.api.v1.RelationshipFilter relationshipFilter_;

    /**
     * <pre>
     * relationship_filter defines the filter to be applied to the relationships
     * to be returned.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the relationshipFilter field is set.
     */
    @java.lang.Override
    public boolean hasRelationshipFilter() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <pre>
     * relationship_filter defines the filter to be applied to the relationships
     * to be returned.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The relationshipFilter.
     */
    @java.lang.Override
    public com.authzed.api.v1.RelationshipFilter getRelationshipFilter() {
        return relationshipFilter_ == null ? com.authzed.api.v1.RelationshipFilter.getDefaultInstance() : relationshipFilter_;
    }

    /**
     * <pre>
     * relationship_filter defines the filter to be applied to the relationships
     * to be returned.
     * </pre>
     *
     * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.RelationshipFilterOrBuilder getRelationshipFilterOrBuilder() {
        return relationshipFilter_ == null ? com.authzed.api.v1.RelationshipFilter.getDefaultInstance() : relationshipFilter_;
    }

    public static final int OPTIONAL_LIMIT_FIELD_NUMBER = 3;

    private int optionalLimit_ = 0;

    /**
     * <pre>
     * optional_limit, if non-zero, specifies the limit on the number of relationships to return
     * before the stream is closed on the server side. By default, the stream will continue
     * resolving relationships until exhausted or the stream is closed due to the client or a
     * network issue.
     * </pre>
     *
     * <code>uint32 optional_limit = 3 [(.validate.rules) = { ... }</code>
     *
     * @return The optionalLimit.
     */
    @java.lang.Override
    public int getOptionalLimit() {
        return optionalLimit_;
    }

    public static final int OPTIONAL_CURSOR_FIELD_NUMBER = 4;

    private com.authzed.api.v1.Cursor optionalCursor_;

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
     * The cursor can be found on the ReadRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
     *
     * @return Whether the optionalCursor field is set.
     */
    @java.lang.Override
    public boolean hasOptionalCursor() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
     * The cursor can be found on the ReadRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
     *
     * @return The optionalCursor.
     */
    @java.lang.Override
    public com.authzed.api.v1.Cursor getOptionalCursor() {
        return optionalCursor_ == null ? com.authzed.api.v1.Cursor.getDefaultInstance() : optionalCursor_;
    }

    /**
     * <pre>
     * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
     * The cursor can be found on the ReadRelationshipsResponse object.
     * </pre>
     *
     * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.CursorOrBuilder getOptionalCursorOrBuilder() {
        return optionalCursor_ == null ? com.authzed.api.v1.Cursor.getDefaultInstance() : optionalCursor_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getConsistency());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(2, getRelationshipFilter());
        }
        if (optionalLimit_ != 0) {
            output.writeUInt32(3, optionalLimit_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            output.writeMessage(4, getOptionalCursor());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getConsistency());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getRelationshipFilter());
        }
        if (optionalLimit_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeUInt32Size(3, optionalLimit_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getOptionalCursor());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.ReadRelationshipsRequest)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.ReadRelationshipsRequest other = (com.authzed.api.v1.ReadRelationshipsRequest) obj;
        if (hasConsistency() != other.hasConsistency())
            return false;
        if (hasConsistency()) {
            if (!getConsistency().equals(other.getConsistency()))
                return false;
        }
        if (hasRelationshipFilter() != other.hasRelationshipFilter())
            return false;
        if (hasRelationshipFilter()) {
            if (!getRelationshipFilter().equals(other.getRelationshipFilter()))
                return false;
        }
        if (getOptionalLimit() != other.getOptionalLimit())
            return false;
        if (hasOptionalCursor() != other.hasOptionalCursor())
            return false;
        if (hasOptionalCursor()) {
            if (!getOptionalCursor().equals(other.getOptionalCursor()))
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasConsistency()) {
            hash = (37 * hash) + CONSISTENCY_FIELD_NUMBER;
            hash = (53 * hash) + getConsistency().hashCode();
        }
        if (hasRelationshipFilter()) {
            hash = (37 * hash) + RELATIONSHIP_FILTER_FIELD_NUMBER;
            hash = (53 * hash) + getRelationshipFilter().hashCode();
        }
        hash = (37 * hash) + OPTIONAL_LIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getOptionalLimit();
        if (hasOptionalCursor()) {
            hash = (37 * hash) + OPTIONAL_CURSOR_FIELD_NUMBER;
            hash = (53 * hash) + getOptionalCursor().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.ReadRelationshipsRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * ReadRelationshipsRequest specifies one or more filters used to read matching
     * relationships within the system.
     * </pre>
     *
     * Protobuf type {@code authzed.api.v1.ReadRelationshipsRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.ReadRelationshipsRequest)
            com.authzed.api.v1.ReadRelationshipsRequestOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ReadRelationshipsRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReadRelationshipsRequest.class,
                            com.authzed.api.v1.ReadRelationshipsRequest.Builder.class);
        }

        // Construct using com.authzed.api.v1.ReadRelationshipsRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                internalGetConsistencyFieldBuilder();
                internalGetRelationshipFilterFieldBuilder();
                internalGetOptionalCursorFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            consistency_ = null;
            if (consistencyBuilder_ != null) {
                consistencyBuilder_.dispose();
                consistencyBuilder_ = null;
            }
            relationshipFilter_ = null;
            if (relationshipFilterBuilder_ != null) {
                relationshipFilterBuilder_.dispose();
                relationshipFilterBuilder_ = null;
            }
            optionalLimit_ = 0;
            optionalCursor_ = null;
            if (optionalCursorBuilder_ != null) {
                optionalCursorBuilder_.dispose();
                optionalCursorBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.PermissionService.internal_static_authzed_api_v1_ReadRelationshipsRequest_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReadRelationshipsRequest getDefaultInstanceForType() {
            return com.authzed.api.v1.ReadRelationshipsRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.ReadRelationshipsRequest build() {
            com.authzed.api.v1.ReadRelationshipsRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReadRelationshipsRequest buildPartial() {
            com.authzed.api.v1.ReadRelationshipsRequest result = new com.authzed.api.v1.ReadRelationshipsRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.authzed.api.v1.ReadRelationshipsRequest result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.consistency_ = consistencyBuilder_ == null ? consistency_ : consistencyBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.relationshipFilter_ = relationshipFilterBuilder_ == null ? relationshipFilter_
                        : relationshipFilterBuilder_.build();
                to_bitField0_ |= 0x00000002;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.optionalLimit_ = optionalLimit_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.optionalCursor_ = optionalCursorBuilder_ == null ? optionalCursor_ : optionalCursorBuilder_.build();
                to_bitField0_ |= 0x00000004;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.ReadRelationshipsRequest) {
                return mergeFrom((com.authzed.api.v1.ReadRelationshipsRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.ReadRelationshipsRequest other) {
            if (other == com.authzed.api.v1.ReadRelationshipsRequest.getDefaultInstance())
                return this;
            if (other.hasConsistency()) {
                mergeConsistency(other.getConsistency());
            }
            if (other.hasRelationshipFilter()) {
                mergeRelationshipFilter(other.getRelationshipFilter());
            }
            if (other.getOptionalLimit() != 0) {
                setOptionalLimit(other.getOptionalLimit());
            }
            if (other.hasOptionalCursor()) {
                mergeOptionalCursor(other.getOptionalCursor());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(internalGetConsistencyFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            input.readMessage(internalGetRelationshipFilterFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000002;
                            break;
                        }
                        // case 18
                        case 24: {
                            optionalLimit_ = input.readUInt32();
                            bitField0_ |= 0x00000004;
                            break;
                        }
                        // case 24
                        case 34: {
                            input.readMessage(internalGetOptionalCursorFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000008;
                            break;
                        }
                        // case 34
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private com.authzed.api.v1.Consistency consistency_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder> consistencyBuilder_;

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         *
         * @return Whether the consistency field is set.
         */
        public boolean hasConsistency() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         *
         * @return The consistency.
         */
        public com.authzed.api.v1.Consistency getConsistency() {
            if (consistencyBuilder_ == null) {
                return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
            } else {
                return consistencyBuilder_.getMessage();
            }
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder setConsistency(com.authzed.api.v1.Consistency value) {
            if (consistencyBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                consistency_ = value;
            } else {
                consistencyBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder setConsistency(com.authzed.api.v1.Consistency.Builder builderForValue) {
            if (consistencyBuilder_ == null) {
                consistency_ = builderForValue.build();
            } else {
                consistencyBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder mergeConsistency(com.authzed.api.v1.Consistency value) {
            if (consistencyBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && consistency_ != null
                        && consistency_ != com.authzed.api.v1.Consistency.getDefaultInstance()) {
                    getConsistencyBuilder().mergeFrom(value);
                } else {
                    consistency_ = value;
                }
            } else {
                consistencyBuilder_.mergeFrom(value);
            }
            if (consistency_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public Builder clearConsistency() {
            bitField0_ = (bitField0_ & ~0x00000001);
            consistency_ = null;
            if (consistencyBuilder_ != null) {
                consistencyBuilder_.dispose();
                consistencyBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public com.authzed.api.v1.Consistency.Builder getConsistencyBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return internalGetConsistencyFieldBuilder().getBuilder();
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        public com.authzed.api.v1.ConsistencyOrBuilder getConsistencyOrBuilder() {
            if (consistencyBuilder_ != null) {
                return consistencyBuilder_.getMessageOrBuilder();
            } else {
                return consistency_ == null ? com.authzed.api.v1.Consistency.getDefaultInstance() : consistency_;
            }
        }

        /**
         * <code>.authzed.api.v1.Consistency consistency = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder> internalGetConsistencyFieldBuilder() {
            if (consistencyBuilder_ == null) {
                consistencyBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Consistency, com.authzed.api.v1.Consistency.Builder, com.authzed.api.v1.ConsistencyOrBuilder>(
                        getConsistency(), getParentForChildren(), isClean());
                consistency_ = null;
            }
            return consistencyBuilder_;
        }

        private com.authzed.api.v1.RelationshipFilter relationshipFilter_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.RelationshipFilter, com.authzed.api.v1.RelationshipFilter.Builder, com.authzed.api.v1.RelationshipFilterOrBuilder> relationshipFilterBuilder_;

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         *
         * @return Whether the relationshipFilter field is set.
         */
        public boolean hasRelationshipFilter() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         *
         * @return The relationshipFilter.
         */
        public com.authzed.api.v1.RelationshipFilter getRelationshipFilter() {
            if (relationshipFilterBuilder_ == null) {
                return relationshipFilter_ == null ? com.authzed.api.v1.RelationshipFilter.getDefaultInstance()
                        : relationshipFilter_;
            } else {
                return relationshipFilterBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public Builder setRelationshipFilter(com.authzed.api.v1.RelationshipFilter value) {
            if (relationshipFilterBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                relationshipFilter_ = value;
            } else {
                relationshipFilterBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public Builder setRelationshipFilter(com.authzed.api.v1.RelationshipFilter.Builder builderForValue) {
            if (relationshipFilterBuilder_ == null) {
                relationshipFilter_ = builderForValue.build();
            } else {
                relationshipFilterBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public Builder mergeRelationshipFilter(com.authzed.api.v1.RelationshipFilter value) {
            if (relationshipFilterBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) && relationshipFilter_ != null
                        && relationshipFilter_ != com.authzed.api.v1.RelationshipFilter.getDefaultInstance()) {
                    getRelationshipFilterBuilder().mergeFrom(value);
                } else {
                    relationshipFilter_ = value;
                }
            } else {
                relationshipFilterBuilder_.mergeFrom(value);
            }
            if (relationshipFilter_ != null) {
                bitField0_ |= 0x00000002;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public Builder clearRelationshipFilter() {
            bitField0_ = (bitField0_ & ~0x00000002);
            relationshipFilter_ = null;
            if (relationshipFilterBuilder_ != null) {
                relationshipFilterBuilder_.dispose();
                relationshipFilterBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.RelationshipFilter.Builder getRelationshipFilterBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return internalGetRelationshipFilterFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.RelationshipFilterOrBuilder getRelationshipFilterOrBuilder() {
            if (relationshipFilterBuilder_ != null) {
                return relationshipFilterBuilder_.getMessageOrBuilder();
            } else {
                return relationshipFilter_ == null ? com.authzed.api.v1.RelationshipFilter.getDefaultInstance()
                        : relationshipFilter_;
            }
        }

        /**
         * <pre>
         * relationship_filter defines the filter to be applied to the relationships
         * to be returned.
         * </pre>
         *
         * <code>.authzed.api.v1.RelationshipFilter relationship_filter = 2 [(.validate.rules) = { ... }</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.RelationshipFilter, com.authzed.api.v1.RelationshipFilter.Builder, com.authzed.api.v1.RelationshipFilterOrBuilder> internalGetRelationshipFilterFieldBuilder() {
            if (relationshipFilterBuilder_ == null) {
                relationshipFilterBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.RelationshipFilter, com.authzed.api.v1.RelationshipFilter.Builder, com.authzed.api.v1.RelationshipFilterOrBuilder>(
                        getRelationshipFilter(), getParentForChildren(), isClean());
                relationshipFilter_ = null;
            }
            return relationshipFilterBuilder_;
        }

        private int optionalLimit_;

        /**
         * <pre>
         * optional_limit, if non-zero, specifies the limit on the number of relationships to return
         * before the stream is closed on the server side. By default, the stream will continue
         * resolving relationships until exhausted or the stream is closed due to the client or a
         * network issue.
         * </pre>
         *
         * <code>uint32 optional_limit = 3 [(.validate.rules) = { ... }</code>
         *
         * @return The optionalLimit.
         */
        @java.lang.Override
        public int getOptionalLimit() {
            return optionalLimit_;
        }

        /**
         * <pre>
         * optional_limit, if non-zero, specifies the limit on the number of relationships to return
         * before the stream is closed on the server side. By default, the stream will continue
         * resolving relationships until exhausted or the stream is closed due to the client or a
         * network issue.
         * </pre>
         *
         * <code>uint32 optional_limit = 3 [(.validate.rules) = { ... }</code>
         *
         * @param value The optionalLimit to set.
         * @return This builder for chaining.
         */
        public Builder setOptionalLimit(int value) {
            optionalLimit_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_limit, if non-zero, specifies the limit on the number of relationships to return
         * before the stream is closed on the server side. By default, the stream will continue
         * resolving relationships until exhausted or the stream is closed due to the client or a
         * network issue.
         * </pre>
         *
         * <code>uint32 optional_limit = 3 [(.validate.rules) = { ... }</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearOptionalLimit() {
            bitField0_ = (bitField0_ & ~0x00000004);
            optionalLimit_ = 0;
            onChanged();
            return this;
        }

        private com.authzed.api.v1.Cursor optionalCursor_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Cursor, com.authzed.api.v1.Cursor.Builder, com.authzed.api.v1.CursorOrBuilder> optionalCursorBuilder_;

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         *
         * @return Whether the optionalCursor field is set.
         */
        public boolean hasOptionalCursor() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         *
         * @return The optionalCursor.
         */
        public com.authzed.api.v1.Cursor getOptionalCursor() {
            if (optionalCursorBuilder_ == null) {
                return optionalCursor_ == null ? com.authzed.api.v1.Cursor.getDefaultInstance() : optionalCursor_;
            } else {
                return optionalCursorBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public Builder setOptionalCursor(com.authzed.api.v1.Cursor value) {
            if (optionalCursorBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                optionalCursor_ = value;
            } else {
                optionalCursorBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public Builder setOptionalCursor(com.authzed.api.v1.Cursor.Builder builderForValue) {
            if (optionalCursorBuilder_ == null) {
                optionalCursor_ = builderForValue.build();
            } else {
                optionalCursorBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public Builder mergeOptionalCursor(com.authzed.api.v1.Cursor value) {
            if (optionalCursorBuilder_ == null) {
                if (((bitField0_ & 0x00000008) != 0) && optionalCursor_ != null
                        && optionalCursor_ != com.authzed.api.v1.Cursor.getDefaultInstance()) {
                    getOptionalCursorBuilder().mergeFrom(value);
                } else {
                    optionalCursor_ = value;
                }
            } else {
                optionalCursorBuilder_.mergeFrom(value);
            }
            if (optionalCursor_ != null) {
                bitField0_ |= 0x00000008;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public Builder clearOptionalCursor() {
            bitField0_ = (bitField0_ & ~0x00000008);
            optionalCursor_ = null;
            if (optionalCursorBuilder_ != null) {
                optionalCursorBuilder_.dispose();
                optionalCursorBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public com.authzed.api.v1.Cursor.Builder getOptionalCursorBuilder() {
            bitField0_ |= 0x00000008;
            onChanged();
            return internalGetOptionalCursorFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        public com.authzed.api.v1.CursorOrBuilder getOptionalCursorOrBuilder() {
            if (optionalCursorBuilder_ != null) {
                return optionalCursorBuilder_.getMessageOrBuilder();
            } else {
                return optionalCursor_ == null ? com.authzed.api.v1.Cursor.getDefaultInstance() : optionalCursor_;
            }
        }

        /**
         * <pre>
         * optional_cursor, if specified, indicates the cursor after which results should resume being returned.
         * The cursor can be found on the ReadRelationshipsResponse object.
         * </pre>
         *
         * <code>.authzed.api.v1.Cursor optional_cursor = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Cursor, com.authzed.api.v1.Cursor.Builder, com.authzed.api.v1.CursorOrBuilder> internalGetOptionalCursorFieldBuilder() {
            if (optionalCursorBuilder_ == null) {
                optionalCursorBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.Cursor, com.authzed.api.v1.Cursor.Builder, com.authzed.api.v1.CursorOrBuilder>(
                        getOptionalCursor(), getParentForChildren(), isClean());
                optionalCursor_ = null;
            }
            return optionalCursorBuilder_;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.ReadRelationshipsRequest)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.ReadRelationshipsRequest)
    private static final com.authzed.api.v1.ReadRelationshipsRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.ReadRelationshipsRequest();
    }

    public static com.authzed.api.v1.ReadRelationshipsRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReadRelationshipsRequest> PARSER = new com.google.protobuf.AbstractParser<ReadRelationshipsRequest>() {

        @java.lang.Override
        public ReadRelationshipsRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ReadRelationshipsRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReadRelationshipsRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.ReadRelationshipsRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
