// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ReflectSchemaResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ReflectSchemaResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    java.util.List<com.authzed.api.v1.ReflectionDefinition> getDefinitionsList();

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    com.authzed.api.v1.ReflectionDefinition getDefinitions(int index);

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    int getDefinitionsCount();

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ReflectionDefinitionOrBuilder> getDefinitionsOrBuilderList();

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    com.authzed.api.v1.ReflectionDefinitionOrBuilder getDefinitionsOrBuilder(int index);

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    java.util.List<com.authzed.api.v1.ReflectionCaveat> getCaveatsList();

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    com.authzed.api.v1.ReflectionCaveat getCaveats(int index);

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    int getCaveatsCount();

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ReflectionCaveatOrBuilder> getCaveatsOrBuilderList();

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    com.authzed.api.v1.ReflectionCaveatOrBuilder getCaveatsOrBuilder(int index);

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     *
     * @return Whether the readAt field is set.
     */
    boolean hasReadAt();

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     *
     * @return The readAt.
     */
    com.authzed.api.v1.ZedToken getReadAt();

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getReadAtOrBuilder();
}
