// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ReflectionRelationReferenceOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ReflectionRelationReference)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string definition_name = 1;</code>
     *
     * @return The definitionName.
     */
    java.lang.String getDefinitionName();

    /**
     * <code>string definition_name = 1;</code>
     *
     * @return The bytes for definitionName.
     */
    com.google.protobuf.ByteString getDefinitionNameBytes();

    /**
     * <code>string relation_name = 2;</code>
     *
     * @return The relationName.
     */
    java.lang.String getRelationName();

    /**
     * <code>string relation_name = 2;</code>
     *
     * @return The bytes for relationName.
     */
    com.google.protobuf.ByteString getRelationNameBytes();

    /**
     * <code>bool is_permission = 3;</code>
     *
     * @return The isPermission.
     */
    boolean getIsPermission();
}
