// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

@com.google.protobuf.Generated
public interface ReflectionCaveatOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.v1.ReflectionCaveat)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <pre>
     * comment is a human-readable comments on the caveat. Will include
     * delimiter characters.
     * </pre>
     *
     * <code>string comment = 2;</code>
     *
     * @return The comment.
     */
    java.lang.String getComment();

    /**
     * <pre>
     * comment is a human-readable comments on the caveat. Will include
     * delimiter characters.
     * </pre>
     *
     * <code>string comment = 2;</code>
     *
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString getCommentBytes();

    /**
     * <code>repeated .authzed.api.v1.ReflectionCaveatParameter parameters = 3;</code>
     */
    java.util.List<com.authzed.api.v1.ReflectionCaveatParameter> getParametersList();

    /**
     * <code>repeated .authzed.api.v1.ReflectionCaveatParameter parameters = 3;</code>
     */
    com.authzed.api.v1.ReflectionCaveatParameter getParameters(int index);

    /**
     * <code>repeated .authzed.api.v1.ReflectionCaveatParameter parameters = 3;</code>
     */
    int getParametersCount();

    /**
     * <code>repeated .authzed.api.v1.ReflectionCaveatParameter parameters = 3;</code>
     */
    java.util.List<? extends com.authzed.api.v1.ReflectionCaveatParameterOrBuilder> getParametersOrBuilderList();

    /**
     * <code>repeated .authzed.api.v1.ReflectionCaveatParameter parameters = 3;</code>
     */
    com.authzed.api.v1.ReflectionCaveatParameterOrBuilder getParametersOrBuilder(int index);

    /**
     * <code>string expression = 4;</code>
     *
     * @return The expression.
     */
    java.lang.String getExpression();

    /**
     * <code>string expression = 4;</code>
     *
     * @return The bytes for expression.
     */
    com.google.protobuf.ByteString getExpressionBytes();
}
