// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * Protobuf type {@code authzed.api.v1.ReflectionRelationSubjectTypeChange}
 */
@com.google.protobuf.Generated
public final class ReflectionRelationSubjectTypeChange extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.ReflectionRelationSubjectTypeChange)
        ReflectionRelationSubjectTypeChangeOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", ReflectionRelationSubjectTypeChange.class.getName());
    }

    // Use ReflectionRelationSubjectTypeChange.newBuilder() to construct.
    private ReflectionRelationSubjectTypeChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ReflectionRelationSubjectTypeChange() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectionRelationSubjectTypeChange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectionRelationSubjectTypeChange_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReflectionRelationSubjectTypeChange.class,
                        com.authzed.api.v1.ReflectionRelationSubjectTypeChange.Builder.class);
    }

    private int bitField0_;

    public static final int RELATION_FIELD_NUMBER = 1;

    private com.authzed.api.v1.ReflectionRelation relation_;

    /**
     * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
     *
     * @return Whether the relation field is set.
     */
    @java.lang.Override
    public boolean hasRelation() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
     *
     * @return The relation.
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionRelation getRelation() {
        return relation_ == null ? com.authzed.api.v1.ReflectionRelation.getDefaultInstance() : relation_;
    }

    /**
     * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionRelationOrBuilder getRelationOrBuilder() {
        return relation_ == null ? com.authzed.api.v1.ReflectionRelation.getDefaultInstance() : relation_;
    }

    public static final int CHANGED_SUBJECT_TYPE_FIELD_NUMBER = 2;

    private com.authzed.api.v1.ReflectionTypeReference changedSubjectType_;

    /**
     * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
     *
     * @return Whether the changedSubjectType field is set.
     */
    @java.lang.Override
    public boolean hasChangedSubjectType() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
     *
     * @return The changedSubjectType.
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionTypeReference getChangedSubjectType() {
        return changedSubjectType_ == null ? com.authzed.api.v1.ReflectionTypeReference.getDefaultInstance()
                : changedSubjectType_;
    }

    /**
     * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionTypeReferenceOrBuilder getChangedSubjectTypeOrBuilder() {
        return changedSubjectType_ == null ? com.authzed.api.v1.ReflectionTypeReference.getDefaultInstance()
                : changedSubjectType_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getRelation());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(2, getChangedSubjectType());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getRelation());
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getChangedSubjectType());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.ReflectionRelationSubjectTypeChange)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.ReflectionRelationSubjectTypeChange other = (com.authzed.api.v1.ReflectionRelationSubjectTypeChange) obj;
        if (hasRelation() != other.hasRelation())
            return false;
        if (hasRelation()) {
            if (!getRelation().equals(other.getRelation()))
                return false;
        }
        if (hasChangedSubjectType() != other.hasChangedSubjectType())
            return false;
        if (hasChangedSubjectType()) {
            if (!getChangedSubjectType().equals(other.getChangedSubjectType()))
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasRelation()) {
            hash = (37 * hash) + RELATION_FIELD_NUMBER;
            hash = (53 * hash) + getRelation().hashCode();
        }
        if (hasChangedSubjectType()) {
            hash = (37 * hash) + CHANGED_SUBJECT_TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getChangedSubjectType().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.ReflectionRelationSubjectTypeChange prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code authzed.api.v1.ReflectionRelationSubjectTypeChange}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.ReflectionRelationSubjectTypeChange)
            com.authzed.api.v1.ReflectionRelationSubjectTypeChangeOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectionRelationSubjectTypeChange_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectionRelationSubjectTypeChange_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReflectionRelationSubjectTypeChange.class,
                            com.authzed.api.v1.ReflectionRelationSubjectTypeChange.Builder.class);
        }

        // Construct using com.authzed.api.v1.ReflectionRelationSubjectTypeChange.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                internalGetRelationFieldBuilder();
                internalGetChangedSubjectTypeFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            relation_ = null;
            if (relationBuilder_ != null) {
                relationBuilder_.dispose();
                relationBuilder_ = null;
            }
            changedSubjectType_ = null;
            if (changedSubjectTypeBuilder_ != null) {
                changedSubjectTypeBuilder_.dispose();
                changedSubjectTypeBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectionRelationSubjectTypeChange_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectionRelationSubjectTypeChange getDefaultInstanceForType() {
            return com.authzed.api.v1.ReflectionRelationSubjectTypeChange.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectionRelationSubjectTypeChange build() {
            com.authzed.api.v1.ReflectionRelationSubjectTypeChange result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectionRelationSubjectTypeChange buildPartial() {
            com.authzed.api.v1.ReflectionRelationSubjectTypeChange result = new com.authzed.api.v1.ReflectionRelationSubjectTypeChange(
                    this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.authzed.api.v1.ReflectionRelationSubjectTypeChange result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.relation_ = relationBuilder_ == null ? relation_ : relationBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.changedSubjectType_ = changedSubjectTypeBuilder_ == null ? changedSubjectType_
                        : changedSubjectTypeBuilder_.build();
                to_bitField0_ |= 0x00000002;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.ReflectionRelationSubjectTypeChange) {
                return mergeFrom((com.authzed.api.v1.ReflectionRelationSubjectTypeChange) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.ReflectionRelationSubjectTypeChange other) {
            if (other == com.authzed.api.v1.ReflectionRelationSubjectTypeChange.getDefaultInstance())
                return this;
            if (other.hasRelation()) {
                mergeRelation(other.getRelation());
            }
            if (other.hasChangedSubjectType()) {
                mergeChangedSubjectType(other.getChangedSubjectType());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(internalGetRelationFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            input.readMessage(internalGetChangedSubjectTypeFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000002;
                            break;
                        }
                        // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private com.authzed.api.v1.ReflectionRelation relation_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionRelation, com.authzed.api.v1.ReflectionRelation.Builder, com.authzed.api.v1.ReflectionRelationOrBuilder> relationBuilder_;

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         *
         * @return Whether the relation field is set.
         */
        public boolean hasRelation() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         *
         * @return The relation.
         */
        public com.authzed.api.v1.ReflectionRelation getRelation() {
            if (relationBuilder_ == null) {
                return relation_ == null ? com.authzed.api.v1.ReflectionRelation.getDefaultInstance() : relation_;
            } else {
                return relationBuilder_.getMessage();
            }
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public Builder setRelation(com.authzed.api.v1.ReflectionRelation value) {
            if (relationBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                relation_ = value;
            } else {
                relationBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public Builder setRelation(com.authzed.api.v1.ReflectionRelation.Builder builderForValue) {
            if (relationBuilder_ == null) {
                relation_ = builderForValue.build();
            } else {
                relationBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public Builder mergeRelation(com.authzed.api.v1.ReflectionRelation value) {
            if (relationBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && relation_ != null
                        && relation_ != com.authzed.api.v1.ReflectionRelation.getDefaultInstance()) {
                    getRelationBuilder().mergeFrom(value);
                } else {
                    relation_ = value;
                }
            } else {
                relationBuilder_.mergeFrom(value);
            }
            if (relation_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public Builder clearRelation() {
            bitField0_ = (bitField0_ & ~0x00000001);
            relation_ = null;
            if (relationBuilder_ != null) {
                relationBuilder_.dispose();
                relationBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public com.authzed.api.v1.ReflectionRelation.Builder getRelationBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return internalGetRelationFieldBuilder().getBuilder();
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        public com.authzed.api.v1.ReflectionRelationOrBuilder getRelationOrBuilder() {
            if (relationBuilder_ != null) {
                return relationBuilder_.getMessageOrBuilder();
            } else {
                return relation_ == null ? com.authzed.api.v1.ReflectionRelation.getDefaultInstance() : relation_;
            }
        }

        /**
         * <code>.authzed.api.v1.ReflectionRelation relation = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionRelation, com.authzed.api.v1.ReflectionRelation.Builder, com.authzed.api.v1.ReflectionRelationOrBuilder> internalGetRelationFieldBuilder() {
            if (relationBuilder_ == null) {
                relationBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionRelation, com.authzed.api.v1.ReflectionRelation.Builder, com.authzed.api.v1.ReflectionRelationOrBuilder>(
                        getRelation(), getParentForChildren(), isClean());
                relation_ = null;
            }
            return relationBuilder_;
        }

        private com.authzed.api.v1.ReflectionTypeReference changedSubjectType_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionTypeReference, com.authzed.api.v1.ReflectionTypeReference.Builder, com.authzed.api.v1.ReflectionTypeReferenceOrBuilder> changedSubjectTypeBuilder_;

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         *
         * @return Whether the changedSubjectType field is set.
         */
        public boolean hasChangedSubjectType() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         *
         * @return The changedSubjectType.
         */
        public com.authzed.api.v1.ReflectionTypeReference getChangedSubjectType() {
            if (changedSubjectTypeBuilder_ == null) {
                return changedSubjectType_ == null ? com.authzed.api.v1.ReflectionTypeReference.getDefaultInstance()
                        : changedSubjectType_;
            } else {
                return changedSubjectTypeBuilder_.getMessage();
            }
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public Builder setChangedSubjectType(com.authzed.api.v1.ReflectionTypeReference value) {
            if (changedSubjectTypeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                changedSubjectType_ = value;
            } else {
                changedSubjectTypeBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public Builder setChangedSubjectType(com.authzed.api.v1.ReflectionTypeReference.Builder builderForValue) {
            if (changedSubjectTypeBuilder_ == null) {
                changedSubjectType_ = builderForValue.build();
            } else {
                changedSubjectTypeBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public Builder mergeChangedSubjectType(com.authzed.api.v1.ReflectionTypeReference value) {
            if (changedSubjectTypeBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0) && changedSubjectType_ != null
                        && changedSubjectType_ != com.authzed.api.v1.ReflectionTypeReference.getDefaultInstance()) {
                    getChangedSubjectTypeBuilder().mergeFrom(value);
                } else {
                    changedSubjectType_ = value;
                }
            } else {
                changedSubjectTypeBuilder_.mergeFrom(value);
            }
            if (changedSubjectType_ != null) {
                bitField0_ |= 0x00000002;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public Builder clearChangedSubjectType() {
            bitField0_ = (bitField0_ & ~0x00000002);
            changedSubjectType_ = null;
            if (changedSubjectTypeBuilder_ != null) {
                changedSubjectTypeBuilder_.dispose();
                changedSubjectTypeBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public com.authzed.api.v1.ReflectionTypeReference.Builder getChangedSubjectTypeBuilder() {
            bitField0_ |= 0x00000002;
            onChanged();
            return internalGetChangedSubjectTypeFieldBuilder().getBuilder();
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        public com.authzed.api.v1.ReflectionTypeReferenceOrBuilder getChangedSubjectTypeOrBuilder() {
            if (changedSubjectTypeBuilder_ != null) {
                return changedSubjectTypeBuilder_.getMessageOrBuilder();
            } else {
                return changedSubjectType_ == null ? com.authzed.api.v1.ReflectionTypeReference.getDefaultInstance()
                        : changedSubjectType_;
            }
        }

        /**
         * <code>.authzed.api.v1.ReflectionTypeReference changed_subject_type = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionTypeReference, com.authzed.api.v1.ReflectionTypeReference.Builder, com.authzed.api.v1.ReflectionTypeReferenceOrBuilder> internalGetChangedSubjectTypeFieldBuilder() {
            if (changedSubjectTypeBuilder_ == null) {
                changedSubjectTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ReflectionTypeReference, com.authzed.api.v1.ReflectionTypeReference.Builder, com.authzed.api.v1.ReflectionTypeReferenceOrBuilder>(
                        getChangedSubjectType(), getParentForChildren(), isClean());
                changedSubjectType_ = null;
            }
            return changedSubjectTypeBuilder_;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.ReflectionRelationSubjectTypeChange)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.ReflectionRelationSubjectTypeChange)
    private static final com.authzed.api.v1.ReflectionRelationSubjectTypeChange DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.ReflectionRelationSubjectTypeChange();
    }

    public static com.authzed.api.v1.ReflectionRelationSubjectTypeChange getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReflectionRelationSubjectTypeChange> PARSER = new com.google.protobuf.AbstractParser<ReflectionRelationSubjectTypeChange>() {

        @java.lang.Override
        public ReflectionRelationSubjectTypeChange parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ReflectionRelationSubjectTypeChange> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReflectionRelationSubjectTypeChange> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.ReflectionRelationSubjectTypeChange getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
