// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/schema_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * Protobuf type {@code authzed.api.v1.ReflectSchemaResponse}
 */
@com.google.protobuf.Generated
public final class ReflectSchemaResponse extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.ReflectSchemaResponse)
        ReflectSchemaResponseOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", ReflectSchemaResponse.class.getName());
    }

    // Use ReflectSchemaResponse.newBuilder() to construct.
    private ReflectSchemaResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ReflectSchemaResponse() {
        definitions_ = java.util.Collections.emptyList();
        caveats_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectSchemaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectSchemaResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReflectSchemaResponse.class,
                        com.authzed.api.v1.ReflectSchemaResponse.Builder.class);
    }

    private int bitField0_;

    public static final int DEFINITIONS_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private java.util.List<com.authzed.api.v1.ReflectionDefinition> definitions_;

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.authzed.api.v1.ReflectionDefinition> getDefinitionsList() {
        return definitions_;
    }

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.authzed.api.v1.ReflectionDefinitionOrBuilder> getDefinitionsOrBuilderList() {
        return definitions_;
    }

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    @java.lang.Override
    public int getDefinitionsCount() {
        return definitions_.size();
    }

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionDefinition getDefinitions(int index) {
        return definitions_.get(index);
    }

    /**
     * <pre>
     * definitions are the definitions defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionDefinitionOrBuilder getDefinitionsOrBuilder(int index) {
        return definitions_.get(index);
    }

    public static final int CAVEATS_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private java.util.List<com.authzed.api.v1.ReflectionCaveat> caveats_;

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.authzed.api.v1.ReflectionCaveat> getCaveatsList() {
        return caveats_;
    }

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.authzed.api.v1.ReflectionCaveatOrBuilder> getCaveatsOrBuilderList() {
        return caveats_;
    }

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    @java.lang.Override
    public int getCaveatsCount() {
        return caveats_.size();
    }

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionCaveat getCaveats(int index) {
        return caveats_.get(index);
    }

    /**
     * <pre>
     * caveats are the caveats defined in the schema.
     * </pre>
     *
     * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ReflectionCaveatOrBuilder getCaveatsOrBuilder(int index) {
        return caveats_.get(index);
    }

    public static final int READ_AT_FIELD_NUMBER = 3;

    private com.authzed.api.v1.ZedToken readAt_;

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     *
     * @return Whether the readAt field is set.
     */
    @java.lang.Override
    public boolean hasReadAt() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     *
     * @return The readAt.
     */
    @java.lang.Override
    public com.authzed.api.v1.ZedToken getReadAt() {
        return readAt_ == null ? com.authzed.api.v1.ZedToken.getDefaultInstance() : readAt_;
    }

    /**
     * <pre>
     * read_at is the ZedToken at which the schema was read.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ZedTokenOrBuilder getReadAtOrBuilder() {
        return readAt_ == null ? com.authzed.api.v1.ZedToken.getDefaultInstance() : readAt_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        for (int i = 0; i < definitions_.size(); i++) {
            output.writeMessage(1, definitions_.get(i));
        }
        for (int i = 0; i < caveats_.size(); i++) {
            output.writeMessage(2, caveats_.get(i));
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(3, getReadAt());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        for (int i = 0; i < definitions_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, definitions_.get(i));
        }
        for (int i = 0; i < caveats_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, caveats_.get(i));
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getReadAt());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.ReflectSchemaResponse)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.ReflectSchemaResponse other = (com.authzed.api.v1.ReflectSchemaResponse) obj;
        if (!getDefinitionsList().equals(other.getDefinitionsList()))
            return false;
        if (!getCaveatsList().equals(other.getCaveatsList()))
            return false;
        if (hasReadAt() != other.hasReadAt())
            return false;
        if (hasReadAt()) {
            if (!getReadAt().equals(other.getReadAt()))
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getDefinitionsCount() > 0) {
            hash = (37 * hash) + DEFINITIONS_FIELD_NUMBER;
            hash = (53 * hash) + getDefinitionsList().hashCode();
        }
        if (getCaveatsCount() > 0) {
            hash = (37 * hash) + CAVEATS_FIELD_NUMBER;
            hash = (53 * hash) + getCaveatsList().hashCode();
        }
        if (hasReadAt()) {
            hash = (37 * hash) + READ_AT_FIELD_NUMBER;
            hash = (53 * hash) + getReadAt().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ReflectSchemaResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.ReflectSchemaResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code authzed.api.v1.ReflectSchemaResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.ReflectSchemaResponse)
            com.authzed.api.v1.ReflectSchemaResponseOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectSchemaResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectSchemaResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.ReflectSchemaResponse.class,
                            com.authzed.api.v1.ReflectSchemaResponse.Builder.class);
        }

        // Construct using com.authzed.api.v1.ReflectSchemaResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                internalGetDefinitionsFieldBuilder();
                internalGetCaveatsFieldBuilder();
                internalGetReadAtFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            if (definitionsBuilder_ == null) {
                definitions_ = java.util.Collections.emptyList();
            } else {
                definitions_ = null;
                definitionsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            if (caveatsBuilder_ == null) {
                caveats_ = java.util.Collections.emptyList();
            } else {
                caveats_ = null;
                caveatsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            readAt_ = null;
            if (readAtBuilder_ != null) {
                readAtBuilder_.dispose();
                readAtBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.SchemaServiceOuterClass.internal_static_authzed_api_v1_ReflectSchemaResponse_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectSchemaResponse getDefaultInstanceForType() {
            return com.authzed.api.v1.ReflectSchemaResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectSchemaResponse build() {
            com.authzed.api.v1.ReflectSchemaResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.ReflectSchemaResponse buildPartial() {
            com.authzed.api.v1.ReflectSchemaResponse result = new com.authzed.api.v1.ReflectSchemaResponse(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(com.authzed.api.v1.ReflectSchemaResponse result) {
            if (definitionsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    definitions_ = java.util.Collections.unmodifiableList(definitions_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.definitions_ = definitions_;
            } else {
                result.definitions_ = definitionsBuilder_.build();
            }
            if (caveatsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    caveats_ = java.util.Collections.unmodifiableList(caveats_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.caveats_ = caveats_;
            } else {
                result.caveats_ = caveatsBuilder_.build();
            }
        }

        private void buildPartial0(com.authzed.api.v1.ReflectSchemaResponse result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.readAt_ = readAtBuilder_ == null ? readAt_ : readAtBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.ReflectSchemaResponse) {
                return mergeFrom((com.authzed.api.v1.ReflectSchemaResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.ReflectSchemaResponse other) {
            if (other == com.authzed.api.v1.ReflectSchemaResponse.getDefaultInstance())
                return this;
            if (definitionsBuilder_ == null) {
                if (!other.definitions_.isEmpty()) {
                    if (definitions_.isEmpty()) {
                        definitions_ = other.definitions_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureDefinitionsIsMutable();
                        definitions_.addAll(other.definitions_);
                    }
                    onChanged();
                }
            } else {
                if (!other.definitions_.isEmpty()) {
                    if (definitionsBuilder_.isEmpty()) {
                        definitionsBuilder_.dispose();
                        definitionsBuilder_ = null;
                        definitions_ = other.definitions_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        definitionsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                ? internalGetDefinitionsFieldBuilder()
                                : null;
                    } else {
                        definitionsBuilder_.addAllMessages(other.definitions_);
                    }
                }
            }
            if (caveatsBuilder_ == null) {
                if (!other.caveats_.isEmpty()) {
                    if (caveats_.isEmpty()) {
                        caveats_ = other.caveats_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureCaveatsIsMutable();
                        caveats_.addAll(other.caveats_);
                    }
                    onChanged();
                }
            } else {
                if (!other.caveats_.isEmpty()) {
                    if (caveatsBuilder_.isEmpty()) {
                        caveatsBuilder_.dispose();
                        caveatsBuilder_ = null;
                        caveats_ = other.caveats_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        caveatsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                ? internalGetCaveatsFieldBuilder()
                                : null;
                    } else {
                        caveatsBuilder_.addAllMessages(other.caveats_);
                    }
                }
            }
            if (other.hasReadAt()) {
                mergeReadAt(other.getReadAt());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.authzed.api.v1.ReflectionDefinition m = input
                                    .readMessage(com.authzed.api.v1.ReflectionDefinition.parser(), extensionRegistry);
                            if (definitionsBuilder_ == null) {
                                ensureDefinitionsIsMutable();
                                definitions_.add(m);
                            } else {
                                definitionsBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 10
                        case 18: {
                            com.authzed.api.v1.ReflectionCaveat m = input
                                    .readMessage(com.authzed.api.v1.ReflectionCaveat.parser(), extensionRegistry);
                            if (caveatsBuilder_ == null) {
                                ensureCaveatsIsMutable();
                                caveats_.add(m);
                            } else {
                                caveatsBuilder_.addMessage(m);
                            }
                            break;
                        }
                        // case 18
                        case 26: {
                            input.readMessage(internalGetReadAtFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000004;
                            break;
                        }
                        // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private java.util.List<com.authzed.api.v1.ReflectionDefinition> definitions_ = java.util.Collections.emptyList();

        private void ensureDefinitionsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                definitions_ = new java.util.ArrayList<com.authzed.api.v1.ReflectionDefinition>(definitions_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionDefinition, com.authzed.api.v1.ReflectionDefinition.Builder, com.authzed.api.v1.ReflectionDefinitionOrBuilder> definitionsBuilder_;

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public java.util.List<com.authzed.api.v1.ReflectionDefinition> getDefinitionsList() {
            if (definitionsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(definitions_);
            } else {
                return definitionsBuilder_.getMessageList();
            }
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public int getDefinitionsCount() {
            if (definitionsBuilder_ == null) {
                return definitions_.size();
            } else {
                return definitionsBuilder_.getCount();
            }
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public com.authzed.api.v1.ReflectionDefinition getDefinitions(int index) {
            if (definitionsBuilder_ == null) {
                return definitions_.get(index);
            } else {
                return definitionsBuilder_.getMessage(index);
            }
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder setDefinitions(int index, com.authzed.api.v1.ReflectionDefinition value) {
            if (definitionsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDefinitionsIsMutable();
                definitions_.set(index, value);
                onChanged();
            } else {
                definitionsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder setDefinitions(int index, com.authzed.api.v1.ReflectionDefinition.Builder builderForValue) {
            if (definitionsBuilder_ == null) {
                ensureDefinitionsIsMutable();
                definitions_.set(index, builderForValue.build());
                onChanged();
            } else {
                definitionsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder addDefinitions(com.authzed.api.v1.ReflectionDefinition value) {
            if (definitionsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDefinitionsIsMutable();
                definitions_.add(value);
                onChanged();
            } else {
                definitionsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder addDefinitions(int index, com.authzed.api.v1.ReflectionDefinition value) {
            if (definitionsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureDefinitionsIsMutable();
                definitions_.add(index, value);
                onChanged();
            } else {
                definitionsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder addDefinitions(com.authzed.api.v1.ReflectionDefinition.Builder builderForValue) {
            if (definitionsBuilder_ == null) {
                ensureDefinitionsIsMutable();
                definitions_.add(builderForValue.build());
                onChanged();
            } else {
                definitionsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder addDefinitions(int index, com.authzed.api.v1.ReflectionDefinition.Builder builderForValue) {
            if (definitionsBuilder_ == null) {
                ensureDefinitionsIsMutable();
                definitions_.add(index, builderForValue.build());
                onChanged();
            } else {
                definitionsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder addAllDefinitions(java.lang.Iterable<? extends com.authzed.api.v1.ReflectionDefinition> values) {
            if (definitionsBuilder_ == null) {
                ensureDefinitionsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, definitions_);
                onChanged();
            } else {
                definitionsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder clearDefinitions() {
            if (definitionsBuilder_ == null) {
                definitions_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                definitionsBuilder_.clear();
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public Builder removeDefinitions(int index) {
            if (definitionsBuilder_ == null) {
                ensureDefinitionsIsMutable();
                definitions_.remove(index);
                onChanged();
            } else {
                definitionsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public com.authzed.api.v1.ReflectionDefinition.Builder getDefinitionsBuilder(int index) {
            return internalGetDefinitionsFieldBuilder().getBuilder(index);
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public com.authzed.api.v1.ReflectionDefinitionOrBuilder getDefinitionsOrBuilder(int index) {
            if (definitionsBuilder_ == null) {
                return definitions_.get(index);
            } else {
                return definitionsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public java.util.List<? extends com.authzed.api.v1.ReflectionDefinitionOrBuilder> getDefinitionsOrBuilderList() {
            if (definitionsBuilder_ != null) {
                return definitionsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(definitions_);
            }
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public com.authzed.api.v1.ReflectionDefinition.Builder addDefinitionsBuilder() {
            return internalGetDefinitionsFieldBuilder()
                    .addBuilder(com.authzed.api.v1.ReflectionDefinition.getDefaultInstance());
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public com.authzed.api.v1.ReflectionDefinition.Builder addDefinitionsBuilder(int index) {
            return internalGetDefinitionsFieldBuilder().addBuilder(index,
                    com.authzed.api.v1.ReflectionDefinition.getDefaultInstance());
        }

        /**
         * <pre>
         * definitions are the definitions defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionDefinition definitions = 1;</code>
         */
        public java.util.List<com.authzed.api.v1.ReflectionDefinition.Builder> getDefinitionsBuilderList() {
            return internalGetDefinitionsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionDefinition, com.authzed.api.v1.ReflectionDefinition.Builder, com.authzed.api.v1.ReflectionDefinitionOrBuilder> internalGetDefinitionsFieldBuilder() {
            if (definitionsBuilder_ == null) {
                definitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionDefinition, com.authzed.api.v1.ReflectionDefinition.Builder, com.authzed.api.v1.ReflectionDefinitionOrBuilder>(
                        definitions_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
                definitions_ = null;
            }
            return definitionsBuilder_;
        }

        private java.util.List<com.authzed.api.v1.ReflectionCaveat> caveats_ = java.util.Collections.emptyList();

        private void ensureCaveatsIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                caveats_ = new java.util.ArrayList<com.authzed.api.v1.ReflectionCaveat>(caveats_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionCaveat, com.authzed.api.v1.ReflectionCaveat.Builder, com.authzed.api.v1.ReflectionCaveatOrBuilder> caveatsBuilder_;

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public java.util.List<com.authzed.api.v1.ReflectionCaveat> getCaveatsList() {
            if (caveatsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(caveats_);
            } else {
                return caveatsBuilder_.getMessageList();
            }
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public int getCaveatsCount() {
            if (caveatsBuilder_ == null) {
                return caveats_.size();
            } else {
                return caveatsBuilder_.getCount();
            }
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public com.authzed.api.v1.ReflectionCaveat getCaveats(int index) {
            if (caveatsBuilder_ == null) {
                return caveats_.get(index);
            } else {
                return caveatsBuilder_.getMessage(index);
            }
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder setCaveats(int index, com.authzed.api.v1.ReflectionCaveat value) {
            if (caveatsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCaveatsIsMutable();
                caveats_.set(index, value);
                onChanged();
            } else {
                caveatsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder setCaveats(int index, com.authzed.api.v1.ReflectionCaveat.Builder builderForValue) {
            if (caveatsBuilder_ == null) {
                ensureCaveatsIsMutable();
                caveats_.set(index, builderForValue.build());
                onChanged();
            } else {
                caveatsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder addCaveats(com.authzed.api.v1.ReflectionCaveat value) {
            if (caveatsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCaveatsIsMutable();
                caveats_.add(value);
                onChanged();
            } else {
                caveatsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder addCaveats(int index, com.authzed.api.v1.ReflectionCaveat value) {
            if (caveatsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCaveatsIsMutable();
                caveats_.add(index, value);
                onChanged();
            } else {
                caveatsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder addCaveats(com.authzed.api.v1.ReflectionCaveat.Builder builderForValue) {
            if (caveatsBuilder_ == null) {
                ensureCaveatsIsMutable();
                caveats_.add(builderForValue.build());
                onChanged();
            } else {
                caveatsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder addCaveats(int index, com.authzed.api.v1.ReflectionCaveat.Builder builderForValue) {
            if (caveatsBuilder_ == null) {
                ensureCaveatsIsMutable();
                caveats_.add(index, builderForValue.build());
                onChanged();
            } else {
                caveatsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder addAllCaveats(java.lang.Iterable<? extends com.authzed.api.v1.ReflectionCaveat> values) {
            if (caveatsBuilder_ == null) {
                ensureCaveatsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, caveats_);
                onChanged();
            } else {
                caveatsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder clearCaveats() {
            if (caveatsBuilder_ == null) {
                caveats_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                caveatsBuilder_.clear();
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public Builder removeCaveats(int index) {
            if (caveatsBuilder_ == null) {
                ensureCaveatsIsMutable();
                caveats_.remove(index);
                onChanged();
            } else {
                caveatsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public com.authzed.api.v1.ReflectionCaveat.Builder getCaveatsBuilder(int index) {
            return internalGetCaveatsFieldBuilder().getBuilder(index);
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public com.authzed.api.v1.ReflectionCaveatOrBuilder getCaveatsOrBuilder(int index) {
            if (caveatsBuilder_ == null) {
                return caveats_.get(index);
            } else {
                return caveatsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public java.util.List<? extends com.authzed.api.v1.ReflectionCaveatOrBuilder> getCaveatsOrBuilderList() {
            if (caveatsBuilder_ != null) {
                return caveatsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(caveats_);
            }
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public com.authzed.api.v1.ReflectionCaveat.Builder addCaveatsBuilder() {
            return internalGetCaveatsFieldBuilder().addBuilder(com.authzed.api.v1.ReflectionCaveat.getDefaultInstance());
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public com.authzed.api.v1.ReflectionCaveat.Builder addCaveatsBuilder(int index) {
            return internalGetCaveatsFieldBuilder().addBuilder(index, com.authzed.api.v1.ReflectionCaveat.getDefaultInstance());
        }

        /**
         * <pre>
         * caveats are the caveats defined in the schema.
         * </pre>
         *
         * <code>repeated .authzed.api.v1.ReflectionCaveat caveats = 2;</code>
         */
        public java.util.List<com.authzed.api.v1.ReflectionCaveat.Builder> getCaveatsBuilderList() {
            return internalGetCaveatsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionCaveat, com.authzed.api.v1.ReflectionCaveat.Builder, com.authzed.api.v1.ReflectionCaveatOrBuilder> internalGetCaveatsFieldBuilder() {
            if (caveatsBuilder_ == null) {
                caveatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.authzed.api.v1.ReflectionCaveat, com.authzed.api.v1.ReflectionCaveat.Builder, com.authzed.api.v1.ReflectionCaveatOrBuilder>(
                        caveats_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
                caveats_ = null;
            }
            return caveatsBuilder_;
        }

        private com.authzed.api.v1.ZedToken readAt_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ZedToken, com.authzed.api.v1.ZedToken.Builder, com.authzed.api.v1.ZedTokenOrBuilder> readAtBuilder_;

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         *
         * @return Whether the readAt field is set.
         */
        public boolean hasReadAt() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         *
         * @return The readAt.
         */
        public com.authzed.api.v1.ZedToken getReadAt() {
            if (readAtBuilder_ == null) {
                return readAt_ == null ? com.authzed.api.v1.ZedToken.getDefaultInstance() : readAt_;
            } else {
                return readAtBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public Builder setReadAt(com.authzed.api.v1.ZedToken value) {
            if (readAtBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                readAt_ = value;
            } else {
                readAtBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public Builder setReadAt(com.authzed.api.v1.ZedToken.Builder builderForValue) {
            if (readAtBuilder_ == null) {
                readAt_ = builderForValue.build();
            } else {
                readAtBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public Builder mergeReadAt(com.authzed.api.v1.ZedToken value) {
            if (readAtBuilder_ == null) {
                if (((bitField0_ & 0x00000004) != 0) && readAt_ != null
                        && readAt_ != com.authzed.api.v1.ZedToken.getDefaultInstance()) {
                    getReadAtBuilder().mergeFrom(value);
                } else {
                    readAt_ = value;
                }
            } else {
                readAtBuilder_.mergeFrom(value);
            }
            if (readAt_ != null) {
                bitField0_ |= 0x00000004;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public Builder clearReadAt() {
            bitField0_ = (bitField0_ & ~0x00000004);
            readAt_ = null;
            if (readAtBuilder_ != null) {
                readAtBuilder_.dispose();
                readAtBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public com.authzed.api.v1.ZedToken.Builder getReadAtBuilder() {
            bitField0_ |= 0x00000004;
            onChanged();
            return internalGetReadAtFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        public com.authzed.api.v1.ZedTokenOrBuilder getReadAtOrBuilder() {
            if (readAtBuilder_ != null) {
                return readAtBuilder_.getMessageOrBuilder();
            } else {
                return readAt_ == null ? com.authzed.api.v1.ZedToken.getDefaultInstance() : readAt_;
            }
        }

        /**
         * <pre>
         * read_at is the ZedToken at which the schema was read.
         * </pre>
         *
         * <code>.authzed.api.v1.ZedToken read_at = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ZedToken, com.authzed.api.v1.ZedToken.Builder, com.authzed.api.v1.ZedTokenOrBuilder> internalGetReadAtFieldBuilder() {
            if (readAtBuilder_ == null) {
                readAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ZedToken, com.authzed.api.v1.ZedToken.Builder, com.authzed.api.v1.ZedTokenOrBuilder>(
                        getReadAt(), getParentForChildren(), isClean());
                readAt_ = null;
            }
            return readAtBuilder_;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.ReflectSchemaResponse)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.ReflectSchemaResponse)
    private static final com.authzed.api.v1.ReflectSchemaResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.ReflectSchemaResponse();
    }

    public static com.authzed.api.v1.ReflectSchemaResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReflectSchemaResponse> PARSER = new com.google.protobuf.AbstractParser<ReflectSchemaResponse>() {

        @java.lang.Override
        public ReflectSchemaResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ReflectSchemaResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReflectSchemaResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.ReflectSchemaResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
