// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/core.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * <pre>
 * Relationship specifies how a resource relates to a subject. Relationships
 * form the data for the graph over which all permissions questions are
 * answered.
 * </pre>
 *
 * Protobuf type {@code authzed.api.v1.Relationship}
 */
@com.google.protobuf.Generated
public final class Relationship extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.Relationship)
        RelationshipOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", Relationship.class.getName());
    }

    // Use Relationship.newBuilder() to construct.
    private Relationship(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private Relationship() {
        relation_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.Core.internal_static_authzed_api_v1_Relationship_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.Core.internal_static_authzed_api_v1_Relationship_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.Relationship.class,
                        com.authzed.api.v1.Relationship.Builder.class);
    }

    private int bitField0_;

    public static final int RESOURCE_FIELD_NUMBER = 1;

    private com.authzed.api.v1.ObjectReference resource_;

    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the resource field is set.
     */
    @java.lang.Override
    public boolean hasResource() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The resource.
     */
    @java.lang.Override
    public com.authzed.api.v1.ObjectReference getResource() {
        return resource_ == null ? com.authzed.api.v1.ObjectReference.getDefaultInstance() : resource_;
    }

    /**
     * <pre>
     * resource is the resource to which the subject is related, in some manner
     * </pre>
     *
     * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ObjectReferenceOrBuilder getResourceOrBuilder() {
        return resource_ == null ? com.authzed.api.v1.ObjectReference.getDefaultInstance() : resource_;
    }

    public static final int RELATION_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object relation_ = "";

    /**
     * <pre>
     * relation is how the resource and subject are related.
     * </pre>
     *
     * <code>string relation = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The relation.
     */
    @java.lang.Override
    public java.lang.String getRelation() {
        java.lang.Object ref = relation_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            relation_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * relation is how the resource and subject are related.
     * </pre>
     *
     * <code>string relation = 2 [(.validate.rules) = { ... }</code>
     *
     * @return The bytes for relation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRelationBytes() {
        java.lang.Object ref = relation_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            relation_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;

    private com.authzed.api.v1.SubjectReference subject_;

    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the subject field is set.
     */
    @java.lang.Override
    public boolean hasSubject() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
     *
     * @return The subject.
     */
    @java.lang.Override
    public com.authzed.api.v1.SubjectReference getSubject() {
        return subject_ == null ? com.authzed.api.v1.SubjectReference.getDefaultInstance() : subject_;
    }

    /**
     * <pre>
     * subject is the subject to which the resource is related, in some manner.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
        return subject_ == null ? com.authzed.api.v1.SubjectReference.getDefaultInstance() : subject_;
    }

    public static final int OPTIONAL_CAVEAT_FIELD_NUMBER = 4;

    private com.authzed.api.v1.ContextualizedCaveat optionalCaveat_;

    /**
     * <pre>
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     * </pre>
     *
     * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
     *
     * @return Whether the optionalCaveat field is set.
     */
    @java.lang.Override
    public boolean hasOptionalCaveat() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <pre>
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     * </pre>
     *
     * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
     *
     * @return The optionalCaveat.
     */
    @java.lang.Override
    public com.authzed.api.v1.ContextualizedCaveat getOptionalCaveat() {
        return optionalCaveat_ == null ? com.authzed.api.v1.ContextualizedCaveat.getDefaultInstance() : optionalCaveat_;
    }

    /**
     * <pre>
     * optional_caveat is a reference to a the caveat that must be enforced over the relationship
     * </pre>
     *
     * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
     */
    @java.lang.Override
    public com.authzed.api.v1.ContextualizedCaveatOrBuilder getOptionalCaveatOrBuilder() {
        return optionalCaveat_ == null ? com.authzed.api.v1.ContextualizedCaveat.getDefaultInstance() : optionalCaveat_;
    }

    public static final int OPTIONAL_EXPIRES_AT_FIELD_NUMBER = 5;

    private com.google.protobuf.Timestamp optionalExpiresAt_;

    /**
     * <pre>
     * optional_expires_at is the time at which the relationship expires, if any.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     *
     * @return Whether the optionalExpiresAt field is set.
     */
    @java.lang.Override
    public boolean hasOptionalExpiresAt() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <pre>
     * optional_expires_at is the time at which the relationship expires, if any.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     *
     * @return The optionalExpiresAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getOptionalExpiresAt() {
        return optionalExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : optionalExpiresAt_;
    }

    /**
     * <pre>
     * optional_expires_at is the time at which the relationship expires, if any.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getOptionalExpiresAtOrBuilder() {
        return optionalExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : optionalExpiresAt_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(1, getResource());
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relation_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, relation_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            output.writeMessage(3, getSubject());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            output.writeMessage(4, getOptionalCaveat());
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            output.writeMessage(5, getOptionalExpiresAt());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResource());
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(relation_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, relation_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getSubject());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getOptionalCaveat());
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, getOptionalExpiresAt());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.Relationship)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.Relationship other = (com.authzed.api.v1.Relationship) obj;
        if (hasResource() != other.hasResource())
            return false;
        if (hasResource()) {
            if (!getResource().equals(other.getResource()))
                return false;
        }
        if (!getRelation().equals(other.getRelation()))
            return false;
        if (hasSubject() != other.hasSubject())
            return false;
        if (hasSubject()) {
            if (!getSubject().equals(other.getSubject()))
                return false;
        }
        if (hasOptionalCaveat() != other.hasOptionalCaveat())
            return false;
        if (hasOptionalCaveat()) {
            if (!getOptionalCaveat().equals(other.getOptionalCaveat()))
                return false;
        }
        if (hasOptionalExpiresAt() != other.hasOptionalExpiresAt())
            return false;
        if (hasOptionalExpiresAt()) {
            if (!getOptionalExpiresAt().equals(other.getOptionalExpiresAt()))
                return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasResource()) {
            hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
            hash = (53 * hash) + getResource().hashCode();
        }
        hash = (37 * hash) + RELATION_FIELD_NUMBER;
        hash = (53 * hash) + getRelation().hashCode();
        if (hasSubject()) {
            hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
            hash = (53 * hash) + getSubject().hashCode();
        }
        if (hasOptionalCaveat()) {
            hash = (37 * hash) + OPTIONAL_CAVEAT_FIELD_NUMBER;
            hash = (53 * hash) + getOptionalCaveat().hashCode();
        }
        if (hasOptionalExpiresAt()) {
            hash = (37 * hash) + OPTIONAL_EXPIRES_AT_FIELD_NUMBER;
            hash = (53 * hash) + getOptionalExpiresAt().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.Relationship parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.Relationship parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.Relationship parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.Relationship parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.Relationship parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.Relationship parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.Relationship parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.Relationship parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.Relationship parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.Relationship parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.Relationship parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.Relationship parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.Relationship prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Relationship specifies how a resource relates to a subject. Relationships
     * form the data for the graph over which all permissions questions are
     * answered.
     * </pre>
     *
     * Protobuf type {@code authzed.api.v1.Relationship}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.Relationship)
            com.authzed.api.v1.RelationshipOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_Relationship_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_Relationship_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.Relationship.class,
                            com.authzed.api.v1.Relationship.Builder.class);
        }

        // Construct using com.authzed.api.v1.Relationship.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                internalGetResourceFieldBuilder();
                internalGetSubjectFieldBuilder();
                internalGetOptionalCaveatFieldBuilder();
                internalGetOptionalExpiresAtFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            resource_ = null;
            if (resourceBuilder_ != null) {
                resourceBuilder_.dispose();
                resourceBuilder_ = null;
            }
            relation_ = "";
            subject_ = null;
            if (subjectBuilder_ != null) {
                subjectBuilder_.dispose();
                subjectBuilder_ = null;
            }
            optionalCaveat_ = null;
            if (optionalCaveatBuilder_ != null) {
                optionalCaveatBuilder_.dispose();
                optionalCaveatBuilder_ = null;
            }
            optionalExpiresAt_ = null;
            if (optionalExpiresAtBuilder_ != null) {
                optionalExpiresAtBuilder_.dispose();
                optionalExpiresAtBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_Relationship_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.Relationship getDefaultInstanceForType() {
            return com.authzed.api.v1.Relationship.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.Relationship build() {
            com.authzed.api.v1.Relationship result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.Relationship buildPartial() {
            com.authzed.api.v1.Relationship result = new com.authzed.api.v1.Relationship(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.authzed.api.v1.Relationship result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.resource_ = resourceBuilder_ == null ? resource_ : resourceBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.relation_ = relation_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.subject_ = subjectBuilder_ == null ? subject_ : subjectBuilder_.build();
                to_bitField0_ |= 0x00000002;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.optionalCaveat_ = optionalCaveatBuilder_ == null ? optionalCaveat_ : optionalCaveatBuilder_.build();
                to_bitField0_ |= 0x00000004;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.optionalExpiresAt_ = optionalExpiresAtBuilder_ == null ? optionalExpiresAt_
                        : optionalExpiresAtBuilder_.build();
                to_bitField0_ |= 0x00000008;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.Relationship) {
                return mergeFrom((com.authzed.api.v1.Relationship) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.Relationship other) {
            if (other == com.authzed.api.v1.Relationship.getDefaultInstance())
                return this;
            if (other.hasResource()) {
                mergeResource(other.getResource());
            }
            if (!other.getRelation().isEmpty()) {
                relation_ = other.relation_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.hasSubject()) {
                mergeSubject(other.getSubject());
            }
            if (other.hasOptionalCaveat()) {
                mergeOptionalCaveat(other.getOptionalCaveat());
            }
            if (other.hasOptionalExpiresAt()) {
                mergeOptionalExpiresAt(other.getOptionalExpiresAt());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(internalGetResourceFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        case 18: {
                            relation_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        }
                        // case 18
                        case 26: {
                            input.readMessage(internalGetSubjectFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000004;
                            break;
                        }
                        // case 26
                        case 34: {
                            input.readMessage(internalGetOptionalCaveatFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000008;
                            break;
                        }
                        // case 34
                        case 42: {
                            input.readMessage(internalGetOptionalExpiresAtFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000010;
                            break;
                        }
                        // case 42
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private com.authzed.api.v1.ObjectReference resource_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ObjectReference, com.authzed.api.v1.ObjectReference.Builder, com.authzed.api.v1.ObjectReferenceOrBuilder> resourceBuilder_;

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         *
         * @return Whether the resource field is set.
         */
        public boolean hasResource() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         *
         * @return The resource.
         */
        public com.authzed.api.v1.ObjectReference getResource() {
            if (resourceBuilder_ == null) {
                return resource_ == null ? com.authzed.api.v1.ObjectReference.getDefaultInstance() : resource_;
            } else {
                return resourceBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public Builder setResource(com.authzed.api.v1.ObjectReference value) {
            if (resourceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                resource_ = value;
            } else {
                resourceBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public Builder setResource(com.authzed.api.v1.ObjectReference.Builder builderForValue) {
            if (resourceBuilder_ == null) {
                resource_ = builderForValue.build();
            } else {
                resourceBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public Builder mergeResource(com.authzed.api.v1.ObjectReference value) {
            if (resourceBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && resource_ != null
                        && resource_ != com.authzed.api.v1.ObjectReference.getDefaultInstance()) {
                    getResourceBuilder().mergeFrom(value);
                } else {
                    resource_ = value;
                }
            } else {
                resourceBuilder_.mergeFrom(value);
            }
            if (resource_ != null) {
                bitField0_ |= 0x00000001;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public Builder clearResource() {
            bitField0_ = (bitField0_ & ~0x00000001);
            resource_ = null;
            if (resourceBuilder_ != null) {
                resourceBuilder_.dispose();
                resourceBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.ObjectReference.Builder getResourceBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return internalGetResourceFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.ObjectReferenceOrBuilder getResourceOrBuilder() {
            if (resourceBuilder_ != null) {
                return resourceBuilder_.getMessageOrBuilder();
            } else {
                return resource_ == null ? com.authzed.api.v1.ObjectReference.getDefaultInstance() : resource_;
            }
        }

        /**
         * <pre>
         * resource is the resource to which the subject is related, in some manner
         * </pre>
         *
         * <code>.authzed.api.v1.ObjectReference resource = 1 [(.validate.rules) = { ... }</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ObjectReference, com.authzed.api.v1.ObjectReference.Builder, com.authzed.api.v1.ObjectReferenceOrBuilder> internalGetResourceFieldBuilder() {
            if (resourceBuilder_ == null) {
                resourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ObjectReference, com.authzed.api.v1.ObjectReference.Builder, com.authzed.api.v1.ObjectReferenceOrBuilder>(
                        getResource(), getParentForChildren(), isClean());
                resource_ = null;
            }
            return resourceBuilder_;
        }

        private java.lang.Object relation_ = "";

        /**
         * <pre>
         * relation is how the resource and subject are related.
         * </pre>
         *
         * <code>string relation = 2 [(.validate.rules) = { ... }</code>
         *
         * @return The relation.
         */
        public java.lang.String getRelation() {
            java.lang.Object ref = relation_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                relation_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * relation is how the resource and subject are related.
         * </pre>
         *
         * <code>string relation = 2 [(.validate.rules) = { ... }</code>
         *
         * @return The bytes for relation.
         */
        public com.google.protobuf.ByteString getRelationBytes() {
            java.lang.Object ref = relation_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                relation_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * relation is how the resource and subject are related.
         * </pre>
         *
         * <code>string relation = 2 [(.validate.rules) = { ... }</code>
         *
         * @param value The relation to set.
         * @return This builder for chaining.
         */
        public Builder setRelation(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            relation_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * relation is how the resource and subject are related.
         * </pre>
         *
         * <code>string relation = 2 [(.validate.rules) = { ... }</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRelation() {
            relation_ = getDefaultInstance().getRelation();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * relation is how the resource and subject are related.
         * </pre>
         *
         * <code>string relation = 2 [(.validate.rules) = { ... }</code>
         *
         * @param value The bytes for relation to set.
         * @return This builder for chaining.
         */
        public Builder setRelationBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            relation_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private com.authzed.api.v1.SubjectReference subject_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.SubjectReference, com.authzed.api.v1.SubjectReference.Builder, com.authzed.api.v1.SubjectReferenceOrBuilder> subjectBuilder_;

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         *
         * @return Whether the subject field is set.
         */
        public boolean hasSubject() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         *
         * @return The subject.
         */
        public com.authzed.api.v1.SubjectReference getSubject() {
            if (subjectBuilder_ == null) {
                return subject_ == null ? com.authzed.api.v1.SubjectReference.getDefaultInstance() : subject_;
            } else {
                return subjectBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public Builder setSubject(com.authzed.api.v1.SubjectReference value) {
            if (subjectBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                subject_ = value;
            } else {
                subjectBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public Builder setSubject(com.authzed.api.v1.SubjectReference.Builder builderForValue) {
            if (subjectBuilder_ == null) {
                subject_ = builderForValue.build();
            } else {
                subjectBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public Builder mergeSubject(com.authzed.api.v1.SubjectReference value) {
            if (subjectBuilder_ == null) {
                if (((bitField0_ & 0x00000004) != 0) && subject_ != null
                        && subject_ != com.authzed.api.v1.SubjectReference.getDefaultInstance()) {
                    getSubjectBuilder().mergeFrom(value);
                } else {
                    subject_ = value;
                }
            } else {
                subjectBuilder_.mergeFrom(value);
            }
            if (subject_ != null) {
                bitField0_ |= 0x00000004;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public Builder clearSubject() {
            bitField0_ = (bitField0_ & ~0x00000004);
            subject_ = null;
            if (subjectBuilder_ != null) {
                subjectBuilder_.dispose();
                subjectBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.SubjectReference.Builder getSubjectBuilder() {
            bitField0_ |= 0x00000004;
            onChanged();
            return internalGetSubjectFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
            if (subjectBuilder_ != null) {
                return subjectBuilder_.getMessageOrBuilder();
            } else {
                return subject_ == null ? com.authzed.api.v1.SubjectReference.getDefaultInstance() : subject_;
            }
        }

        /**
         * <pre>
         * subject is the subject to which the resource is related, in some manner.
         * </pre>
         *
         * <code>.authzed.api.v1.SubjectReference subject = 3 [(.validate.rules) = { ... }</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.SubjectReference, com.authzed.api.v1.SubjectReference.Builder, com.authzed.api.v1.SubjectReferenceOrBuilder> internalGetSubjectFieldBuilder() {
            if (subjectBuilder_ == null) {
                subjectBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.SubjectReference, com.authzed.api.v1.SubjectReference.Builder, com.authzed.api.v1.SubjectReferenceOrBuilder>(
                        getSubject(), getParentForChildren(), isClean());
                subject_ = null;
            }
            return subjectBuilder_;
        }

        private com.authzed.api.v1.ContextualizedCaveat optionalCaveat_;

        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ContextualizedCaveat, com.authzed.api.v1.ContextualizedCaveat.Builder, com.authzed.api.v1.ContextualizedCaveatOrBuilder> optionalCaveatBuilder_;

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         *
         * @return Whether the optionalCaveat field is set.
         */
        public boolean hasOptionalCaveat() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         *
         * @return The optionalCaveat.
         */
        public com.authzed.api.v1.ContextualizedCaveat getOptionalCaveat() {
            if (optionalCaveatBuilder_ == null) {
                return optionalCaveat_ == null ? com.authzed.api.v1.ContextualizedCaveat.getDefaultInstance() : optionalCaveat_;
            } else {
                return optionalCaveatBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public Builder setOptionalCaveat(com.authzed.api.v1.ContextualizedCaveat value) {
            if (optionalCaveatBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                optionalCaveat_ = value;
            } else {
                optionalCaveatBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public Builder setOptionalCaveat(com.authzed.api.v1.ContextualizedCaveat.Builder builderForValue) {
            if (optionalCaveatBuilder_ == null) {
                optionalCaveat_ = builderForValue.build();
            } else {
                optionalCaveatBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public Builder mergeOptionalCaveat(com.authzed.api.v1.ContextualizedCaveat value) {
            if (optionalCaveatBuilder_ == null) {
                if (((bitField0_ & 0x00000008) != 0) && optionalCaveat_ != null
                        && optionalCaveat_ != com.authzed.api.v1.ContextualizedCaveat.getDefaultInstance()) {
                    getOptionalCaveatBuilder().mergeFrom(value);
                } else {
                    optionalCaveat_ = value;
                }
            } else {
                optionalCaveatBuilder_.mergeFrom(value);
            }
            if (optionalCaveat_ != null) {
                bitField0_ |= 0x00000008;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public Builder clearOptionalCaveat() {
            bitField0_ = (bitField0_ & ~0x00000008);
            optionalCaveat_ = null;
            if (optionalCaveatBuilder_ != null) {
                optionalCaveatBuilder_.dispose();
                optionalCaveatBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.ContextualizedCaveat.Builder getOptionalCaveatBuilder() {
            bitField0_ |= 0x00000008;
            onChanged();
            return internalGetOptionalCaveatFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        public com.authzed.api.v1.ContextualizedCaveatOrBuilder getOptionalCaveatOrBuilder() {
            if (optionalCaveatBuilder_ != null) {
                return optionalCaveatBuilder_.getMessageOrBuilder();
            } else {
                return optionalCaveat_ == null ? com.authzed.api.v1.ContextualizedCaveat.getDefaultInstance() : optionalCaveat_;
            }
        }

        /**
         * <pre>
         * optional_caveat is a reference to a the caveat that must be enforced over the relationship
         * </pre>
         *
         * <code>.authzed.api.v1.ContextualizedCaveat optional_caveat = 4 [(.validate.rules) = { ... }</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ContextualizedCaveat, com.authzed.api.v1.ContextualizedCaveat.Builder, com.authzed.api.v1.ContextualizedCaveatOrBuilder> internalGetOptionalCaveatFieldBuilder() {
            if (optionalCaveatBuilder_ == null) {
                optionalCaveatBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.authzed.api.v1.ContextualizedCaveat, com.authzed.api.v1.ContextualizedCaveat.Builder, com.authzed.api.v1.ContextualizedCaveatOrBuilder>(
                        getOptionalCaveat(), getParentForChildren(), isClean());
                optionalCaveat_ = null;
            }
            return optionalCaveatBuilder_;
        }

        private com.google.protobuf.Timestamp optionalExpiresAt_;

        private com.google.protobuf.SingleFieldBuilder<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> optionalExpiresAtBuilder_;

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         *
         * @return Whether the optionalExpiresAt field is set.
         */
        public boolean hasOptionalExpiresAt() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         *
         * @return The optionalExpiresAt.
         */
        public com.google.protobuf.Timestamp getOptionalExpiresAt() {
            if (optionalExpiresAtBuilder_ == null) {
                return optionalExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : optionalExpiresAt_;
            } else {
                return optionalExpiresAtBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public Builder setOptionalExpiresAt(com.google.protobuf.Timestamp value) {
            if (optionalExpiresAtBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                optionalExpiresAt_ = value;
            } else {
                optionalExpiresAtBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public Builder setOptionalExpiresAt(com.google.protobuf.Timestamp.Builder builderForValue) {
            if (optionalExpiresAtBuilder_ == null) {
                optionalExpiresAt_ = builderForValue.build();
            } else {
                optionalExpiresAtBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public Builder mergeOptionalExpiresAt(com.google.protobuf.Timestamp value) {
            if (optionalExpiresAtBuilder_ == null) {
                if (((bitField0_ & 0x00000010) != 0) && optionalExpiresAt_ != null
                        && optionalExpiresAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
                    getOptionalExpiresAtBuilder().mergeFrom(value);
                } else {
                    optionalExpiresAt_ = value;
                }
            } else {
                optionalExpiresAtBuilder_.mergeFrom(value);
            }
            if (optionalExpiresAt_ != null) {
                bitField0_ |= 0x00000010;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public Builder clearOptionalExpiresAt() {
            bitField0_ = (bitField0_ & ~0x00000010);
            optionalExpiresAt_ = null;
            if (optionalExpiresAtBuilder_ != null) {
                optionalExpiresAtBuilder_.dispose();
                optionalExpiresAtBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public com.google.protobuf.Timestamp.Builder getOptionalExpiresAtBuilder() {
            bitField0_ |= 0x00000010;
            onChanged();
            return internalGetOptionalExpiresAtFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getOptionalExpiresAtOrBuilder() {
            if (optionalExpiresAtBuilder_ != null) {
                return optionalExpiresAtBuilder_.getMessageOrBuilder();
            } else {
                return optionalExpiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : optionalExpiresAt_;
            }
        }

        /**
         * <pre>
         * optional_expires_at is the time at which the relationship expires, if any.
         * </pre>
         *
         * <code>.google.protobuf.Timestamp optional_expires_at = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> internalGetOptionalExpiresAtFieldBuilder() {
            if (optionalExpiresAtBuilder_ == null) {
                optionalExpiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                        getOptionalExpiresAt(), getParentForChildren(), isClean());
                optionalExpiresAt_ = null;
            }
            return optionalExpiresAtBuilder_;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.Relationship)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.Relationship)
    private static final com.authzed.api.v1.Relationship DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.Relationship();
    }

    public static com.authzed.api.v1.Relationship getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Relationship> PARSER = new com.google.protobuf.AbstractParser<Relationship>() {

        @java.lang.Override
        public Relationship parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Relationship> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Relationship> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.Relationship getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
