// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/watch_service.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * Protobuf enum {@code authzed.api.v1.WatchKind}
 */
@com.google.protobuf.Generated
public enum WatchKind implements com.google.protobuf.ProtocolMessageEnum {

    /**
     * <pre>
     * Default, just relationship updates (for backwards compatibility)
     * </pre>
     *
     * <code>WATCH_KIND_UNSPECIFIED = 0;</code>
     */
    WATCH_KIND_UNSPECIFIED(0),
    /**
     * <code>WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES = 1;</code>
     */
    WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES(1),
    /**
     * <code>WATCH_KIND_INCLUDE_SCHEMA_UPDATES = 2;</code>
     */
    WATCH_KIND_INCLUDE_SCHEMA_UPDATES(2),
    /**
     * <code>WATCH_KIND_INCLUDE_CHECKPOINTS = 3;</code>
     */
    WATCH_KIND_INCLUDE_CHECKPOINTS(3),
    UNRECOGNIZED(-1);

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", WatchKind.class.getName());
    }

    /**
     * <pre>
     * Default, just relationship updates (for backwards compatibility)
     * </pre>
     *
     * <code>WATCH_KIND_UNSPECIFIED = 0;</code>
     */
    public static final int WATCH_KIND_UNSPECIFIED_VALUE = 0;

    /**
     * <code>WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES = 1;</code>
     */
    public static final int WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES_VALUE = 1;

    /**
     * <code>WATCH_KIND_INCLUDE_SCHEMA_UPDATES = 2;</code>
     */
    public static final int WATCH_KIND_INCLUDE_SCHEMA_UPDATES_VALUE = 2;

    /**
     * <code>WATCH_KIND_INCLUDE_CHECKPOINTS = 3;</code>
     */
    public static final int WATCH_KIND_INCLUDE_CHECKPOINTS_VALUE = 3;

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WatchKind valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static WatchKind forNumber(int value) {
        switch (value) {
            case 0:
                return WATCH_KIND_UNSPECIFIED;
            case 1:
                return WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES;
            case 2:
                return WATCH_KIND_INCLUDE_SCHEMA_UPDATES;
            case 3:
                return WATCH_KIND_INCLUDE_CHECKPOINTS;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WatchKind> internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<WatchKind> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<WatchKind>() {

        public WatchKind findValueByNumber(int number) {
            return WatchKind.forNumber(number);
        }
    };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
    }

    public static com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return com.authzed.api.v1.WatchServiceOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final WatchKind[] VALUES = values();

    public static WatchKind valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private WatchKind(int value) {
        this.value = value;
    }
}
