// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/v1/core.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.v1;

/**
 * <pre>
 * ZedToken represents a point in time, or a "revision" in SpiceDB.
 * It is used to provide causality metadata between Write and read requests (Check, ReadRelationships, LookupResources, LookupSubjects)
 * and can also be used to start watching for changes from a specific point in time.
 *
 * See the authzed.api.v1.Consistency message for more information.
 * </pre>
 *
 * Protobuf type {@code authzed.api.v1.ZedToken}
 */
@com.google.protobuf.Generated
public final class ZedToken extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:authzed.api.v1.ZedToken)
        ZedTokenOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
                4, /* minor= */
                32, /* patch= */
                1, /* suffix= */
                "", ZedToken.class.getName());
    }

    // Use ZedToken.newBuilder() to construct.
    private ZedToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ZedToken() {
        token_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.authzed.api.v1.Core.internal_static_authzed_api_v1_ZedToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.authzed.api.v1.Core.internal_static_authzed_api_v1_ZedToken_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.authzed.api.v1.ZedToken.class, com.authzed.api.v1.ZedToken.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";

    /**
     * <code>string token = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            token_ = s;
            return s;
        }
    }

    /**
     * <code>string token = 1 [(.validate.rules) = { ... }</code>
     *
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            token_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, token_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, token_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.authzed.api.v1.ZedToken)) {
            return super.equals(obj);
        }
        com.authzed.api.v1.ZedToken other = (com.authzed.api.v1.ZedToken) obj;
        if (!getToken().equals(other.getToken()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.authzed.api.v1.ZedToken parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ZedToken parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ZedToken parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static com.authzed.api.v1.ZedToken parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.authzed.api.v1.ZedToken prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * ZedToken represents a point in time, or a "revision" in SpiceDB.
     * It is used to provide causality metadata between Write and read requests (Check, ReadRelationships, LookupResources, LookupSubjects)
     * and can also be used to start watching for changes from a specific point in time.
     *
     * See the authzed.api.v1.Consistency message for more information.
     * </pre>
     *
     * Protobuf type {@code authzed.api.v1.ZedToken}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:authzed.api.v1.ZedToken)
            com.authzed.api.v1.ZedTokenOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_ZedToken_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_ZedToken_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.authzed.api.v1.ZedToken.class,
                            com.authzed.api.v1.ZedToken.Builder.class);
        }

        // Construct using com.authzed.api.v1.ZedToken.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            token_ = "";
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.authzed.api.v1.Core.internal_static_authzed_api_v1_ZedToken_descriptor;
        }

        @java.lang.Override
        public com.authzed.api.v1.ZedToken getDefaultInstanceForType() {
            return com.authzed.api.v1.ZedToken.getDefaultInstance();
        }

        @java.lang.Override
        public com.authzed.api.v1.ZedToken build() {
            com.authzed.api.v1.ZedToken result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.authzed.api.v1.ZedToken buildPartial() {
            com.authzed.api.v1.ZedToken result = new com.authzed.api.v1.ZedToken(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.authzed.api.v1.ZedToken result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.token_ = token_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.authzed.api.v1.ZedToken) {
                return mergeFrom((com.authzed.api.v1.ZedToken) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.authzed.api.v1.ZedToken other) {
            if (other == com.authzed.api.v1.ZedToken.getDefaultInstance())
                return this;
            if (!other.getToken().isEmpty()) {
                token_ = other.token_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            token_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                // was an endgroup tag
                                done = true;
                            }
                            break;
                        }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object token_ = "";

        /**
         * <code>string token = 1 [(.validate.rules) = { ... }</code>
         *
         * @return The token.
         */
        public java.lang.String getToken() {
            java.lang.Object ref = token_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                token_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string token = 1 [(.validate.rules) = { ... }</code>
         *
         * @return The bytes for token.
         */
        public com.google.protobuf.ByteString getTokenBytes() {
            java.lang.Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string token = 1 [(.validate.rules) = { ... }</code>
         *
         * @param value The token to set.
         * @return This builder for chaining.
         */
        public Builder setToken(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            token_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string token = 1 [(.validate.rules) = { ... }</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearToken() {
            token_ = getDefaultInstance().getToken();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string token = 1 [(.validate.rules) = { ... }</code>
         *
         * @param value The bytes for token to set.
         * @return This builder for chaining.
         */
        public Builder setTokenBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            token_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        // @@protoc_insertion_point(builder_scope:authzed.api.v1.ZedToken)
    }

    // @@protoc_insertion_point(class_scope:authzed.api.v1.ZedToken)
    private static final com.authzed.api.v1.ZedToken DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.authzed.api.v1.ZedToken();
    }

    public static com.authzed.api.v1.ZedToken getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ZedToken> PARSER = new com.google.protobuf.AbstractParser<ZedToken>() {

        @java.lang.Override
        public ZedToken parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ZedToken> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ZedToken> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.authzed.api.v1.ZedToken getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
