// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissionsets.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface BreakingSchemaChangeOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.BreakingSchemaChange)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * change_at is the revision at which a breaking schema event has happened.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken change_at = 1;</code>
     *
     * @return Whether the changeAt field is set.
     */
    boolean hasChangeAt();

    /**
     * <pre>
     * change_at is the revision at which a breaking schema event has happened.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken change_at = 1;</code>
     *
     * @return The changeAt.
     */
    com.authzed.api.v1.ZedToken getChangeAt();

    /**
     * <pre>
     * change_at is the revision at which a breaking schema event has happened.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken change_at = 1;</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getChangeAtOrBuilder();
}
