// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissionsets.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface DownloadPermissionSetsResponseOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.DownloadPermissionSetsResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * files contains the list of downloadable files with their URLs
     * </pre>
     *
     * <code>repeated .authzed.api.materialize.v0.File files = 1;</code>
     */
    java.util.List<com.authzed.api.materialize.v0.File> getFilesList();

    /**
     * <pre>
     * files contains the list of downloadable files with their URLs
     * </pre>
     *
     * <code>repeated .authzed.api.materialize.v0.File files = 1;</code>
     */
    com.authzed.api.materialize.v0.File getFiles(int index);

    /**
     * <pre>
     * files contains the list of downloadable files with their URLs
     * </pre>
     *
     * <code>repeated .authzed.api.materialize.v0.File files = 1;</code>
     */
    int getFilesCount();

    /**
     * <pre>
     * files contains the list of downloadable files with their URLs
     * </pre>
     *
     * <code>repeated .authzed.api.materialize.v0.File files = 1;</code>
     */
    java.util.List<? extends com.authzed.api.materialize.v0.FileOrBuilder> getFilesOrBuilderList();

    /**
     * <pre>
     * files contains the list of downloadable files with their URLs
     * </pre>
     *
     * <code>repeated .authzed.api.materialize.v0.File files = 1;</code>
     */
    com.authzed.api.materialize.v0.FileOrBuilder getFilesOrBuilder(int index);
}
