// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissionsets.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface FileOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.File)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * name is the filename of the downloadable file
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <pre>
     * name is the filename of the downloadable file
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <pre>
     * url is the download URL for the file (typically a signed S3 URL)
     * </pre>
     *
     * <code>string url = 2;</code>
     *
     * @return The url.
     */
    java.lang.String getUrl();

    /**
     * <pre>
     * url is the download URL for the file (typically a signed S3 URL)
     * </pre>
     *
     * <code>string url = 2;</code>
     *
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString getUrlBytes();
}
