// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissionsets.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface LookupPermissionSetsRequiredOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.LookupPermissionSetsRequired)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * required_lookup_at is the snapshot revision at which the permission set needs to be rebuilt to.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken required_lookup_at = 1;</code>
     *
     * @return Whether the requiredLookupAt field is set.
     */
    boolean hasRequiredLookupAt();

    /**
     * <pre>
     * required_lookup_at is the snapshot revision at which the permission set needs to be rebuilt to.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken required_lookup_at = 1;</code>
     *
     * @return The requiredLookupAt.
     */
    com.authzed.api.v1.ZedToken getRequiredLookupAt();

    /**
     * <pre>
     * required_lookup_at is the snapshot revision at which the permission set needs to be rebuilt to.
     * </pre>
     *
     * <code>.authzed.api.v1.ZedToken required_lookup_at = 1;</code>
     */
    com.authzed.api.v1.ZedTokenOrBuilder getRequiredLookupAtOrBuilder();
}
