// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissionsets.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface MemberReferenceOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.MemberReference)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * object_type is the type of object of a permission set member
     * </pre>
     *
     * <code>string object_type = 1;</code>
     *
     * @return The objectType.
     */
    java.lang.String getObjectType();

    /**
     * <pre>
     * object_type is the type of object of a permission set member
     * </pre>
     *
     * <code>string object_type = 1;</code>
     *
     * @return The bytes for objectType.
     */
    com.google.protobuf.ByteString getObjectTypeBytes();

    /**
     * <pre>
     * object_id is the ID of a permission set member
     * </pre>
     *
     * <code>string object_id = 2;</code>
     *
     * @return The objectId.
     */
    java.lang.String getObjectId();

    /**
     * <pre>
     * object_id is the ID of a permission set member
     * </pre>
     *
     * <code>string object_id = 2;</code>
     *
     * @return The bytes for objectId.
     */
    com.google.protobuf.ByteString getObjectIdBytes();

    /**
     * <pre>
     * optional_permission_or_relation is the permission or relation referenced by this permission set member
     * </pre>
     *
     * <code>string optional_permission_or_relation = 3;</code>
     *
     * @return The optionalPermissionOrRelation.
     */
    java.lang.String getOptionalPermissionOrRelation();

    /**
     * <pre>
     * optional_permission_or_relation is the permission or relation referenced by this permission set member
     * </pre>
     *
     * <code>string optional_permission_or_relation = 3;</code>
     *
     * @return The bytes for optionalPermissionOrRelation.
     */
    com.google.protobuf.ByteString getOptionalPermissionOrRelationBytes();
}
