// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authzed/api/materialize/v0/watchpermissions.proto
// Protobuf Java Version: 4.32.1
package com.authzed.api.materialize.v0;

@com.google.protobuf.Generated
public interface WatchedPermissionOrBuilder extends // @@protoc_insertion_point(interface_extends:authzed.api.materialize.v0.WatchedPermission)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * resource_type is the type of the resource to watch for changes.
     * </pre>
     *
     * <code>string resource_type = 1;</code>
     *
     * @return The resourceType.
     */
    java.lang.String getResourceType();

    /**
     * <pre>
     * resource_type is the type of the resource to watch for changes.
     * </pre>
     *
     * <code>string resource_type = 1;</code>
     *
     * @return The bytes for resourceType.
     */
    com.google.protobuf.ByteString getResourceTypeBytes();

    /**
     * <pre>
     * permission is the permission to watch for changes.
     * </pre>
     *
     * <code>string permission = 2;</code>
     *
     * @return The permission.
     */
    java.lang.String getPermission();

    /**
     * <pre>
     * permission is the permission to watch for changes.
     * </pre>
     *
     * <code>string permission = 2;</code>
     *
     * @return The bytes for permission.
     */
    com.google.protobuf.ByteString getPermissionBytes();

    /**
     * <pre>
     * subject_type is the type of the subject to watch for changes.
     * </pre>
     *
     * <code>string subject_type = 3;</code>
     *
     * @return The subjectType.
     */
    java.lang.String getSubjectType();

    /**
     * <pre>
     * subject_type is the type of the subject to watch for changes.
     * </pre>
     *
     * <code>string subject_type = 3;</code>
     *
     * @return The bytes for subjectType.
     */
    com.google.protobuf.ByteString getSubjectTypeBytes();

    /**
     * <pre>
     * optional_subject_relation is the relation on the subject to watch for changes.
     * </pre>
     *
     * <code>string optional_subject_relation = 4;</code>
     *
     * @return The optionalSubjectRelation.
     */
    java.lang.String getOptionalSubjectRelation();

    /**
     * <pre>
     * optional_subject_relation is the relation on the subject to watch for changes.
     * </pre>
     *
     * <code>string optional_subject_relation = 4;</code>
     *
     * @return The bytes for optionalSubjectRelation.
     */
    com.google.protobuf.ByteString getOptionalSubjectRelationBytes();
}
